function [ddalpha_Body,ddbeta_Body,ddgamma_Body,ddx_Head,ddy_Head,ddz_Head] = FFD_Dds_Body(alpha_Body,beta_Body,dalpha_Body,depth_Body,dgamma_Body,g,gamma_Body,height_Body,l_Alpha_Hand,l_F_X,l_F_Y,l_F_Z,l_Tau_Beta_Shoulder,l_Tau_Alpha_Shoulder,m_Body,r_Alpha_Hand,r_F_X,r_F_Y,r_F_Z,r_Tau_Beta_Shoulder,r_Tau_Alpha_Shoulder,width_Body)
%FFD_DDS_BODY
%    [DDALPHA_BODY,DDBETA_BODY,DDGAMMA_BODY,DDX_HEAD,DDY_HEAD,DDZ_HEAD] = FFD_DDS_BODY(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DEPTH_BODY,DGAMMA_BODY,G,GAMMA_BODY,HEIGHT_BODY,L_ALPHA_HAND,L_F_X,L_F_Y,L_F_Z,L_TAU_BETA_SHOULDER,L_TAU_ALPHA_SHOULDER,M_BODY,R_ALPHA_HAND,R_F_X,R_F_Y,R_F_Z,R_TAU_BETA_SHOULDER,R_TAU_ALPHA_SHOULDER,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:12:55

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = cos(l_Alpha_Hand);
t6 = sin(alpha_Body);
t7 = cos(r_Alpha_Hand);
t8 = sin(beta_Body);
t9 = sin(gamma_Body);
t10 = sin(l_Alpha_Hand);
t11 = sin(r_Alpha_Hand);
t12 = g.*m_Body;
t13 = dalpha_Body.^2;
t14 = depth_Body.^2;
t15 = dgamma_Body.^2;
t16 = height_Body.^2;
t18 = width_Body.^2;
t27 = 1.0./m_Body;
t17 = t16.^2;
t19 = t2.^2;
t20 = t4.^2;
t21 = t6.^2;
t22 = t9.^2;
t23 = l_Tau_Beta_Shoulder.*t5;
t24 = r_Tau_Beta_Shoulder.*t7;
t25 = l_Tau_Beta_Shoulder.*t10;
t26 = r_Tau_Beta_Shoulder.*t11;
t28 = -t12;
t29 = t14.*t16;
t30 = t14+t16;
t31 = t14.*t18;
t32 = t16.*t18;
t33 = t16+t18;
t34 = dalpha_Body.*dgamma_Body.*height_Body.*t6.*t9.*4.0;
t35 = (t2.*t3.*width_Body)./2.0;
t36 = (t2.*t8.*width_Body)./2.0;
t37 = (t3.*t6.*width_Body)./2.0;
t38 = (t6.*t8.*width_Body)./2.0;
t39 = dalpha_Body.*dgamma_Body.*height_Body.*m_Body.*t2.*t9;
t42 = height_Body.*t2.*t4.*t13.*2.0;
t43 = height_Body.*t2.*t4.*t15.*2.0;
t47 = (l_F_X.*t3.*t9.*width_Body)./2.0;
t48 = (r_F_X.*t3.*t9.*width_Body)./2.0;
t49 = (height_Body.*t2.*t4.*t12)./2.0;
t51 = (height_Body.*t6.*t9.*t12)./2.0;
t55 = (height_Body.*m_Body.*t9.*t15)./2.0;
t58 = t2.*t8.*t9.*width_Body.*(-1.0./2.0);
t59 = t3.*t6.*t9.*width_Body.*(-1.0./2.0);
t69 = (height_Body.*m_Body.*t4.*t6.*t13)./2.0;
t70 = (height_Body.*m_Body.*t4.*t6.*t15)./2.0;
t71 = l_F_Y.*t2.*t3.*t4.*width_Body.*(-1.0./2.0);
t72 = l_F_Z.*t3.*t4.*t6.*width_Body.*(-1.0./2.0);
t77 = (m_Body.*t4.*t9.*t15.*t16)./4.0;
t40 = t23+t24;
t41 = t25+t26;
t44 = -t34;
t45 = 1.0./t30;
t46 = 1.0./t33;
t50 = t9.*t35;
t52 = t9.*t36;
t53 = t9.*t37;
t54 = t9.*t38;
t56 = -t48;
t57 = -t49;
t60 = l_F_Y.*t4.*t35;
t61 = r_F_Y.*t4.*t35;
t62 = l_F_Z.*t4.*t37;
t63 = r_F_Z.*t4.*t37;
t65 = -t55;
t66 = t2.*t6.*t17.*t20;
t68 = t2.*t6.*t17.*t22;
t75 = t2.*t6.*t22.*t29;
t76 = t2.*t6.*t20.*t32;
t79 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t9.*t16.*t19)./2.0;
t80 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t9.*t16.*t21)./2.0;
t81 = (m_Body.*t4.*t9.*t13.*t16.*t19)./4.0;
t82 = t19.*t77;
t83 = (m_Body.*t4.*t9.*t13.*t16.*t21)./4.0;
t84 = t21.*t77;
t86 = m_Body.*t4.*t9.*t15.*t16.*t19.*(-1.0./4.0);
t88 = m_Body.*t4.*t9.*t15.*t16.*t21.*(-1.0./4.0);
t91 = t36+t59;
t92 = t37+t58;
t97 = t17+t29+t31+t32;
t104 = l_F_Z+r_F_Z+t28+t39+t69+t70;
t64 = t2.*t40;
t67 = t6.*t41;
t73 = -t68;
t74 = l_F_X+r_F_X+t65;
t78 = -t75;
t85 = -t81;
t87 = -t83;
t89 = t35+t54;
t90 = t38+t50;
t95 = l_F_Y.*t91;
t96 = r_F_Y.*t91;
t100 = 1.0./t97;
t101 = t42+t43+t44;
t93 = l_F_Z.*t90;
t94 = r_F_Z.*t90;
t99 = -t95;
t102 = (m_Body.*t101)./4.0;
t105 = t66+t73+t76+t78;
t107 = t47+t51+t56+t61+t63+t64+t67+t71+t72+t77+t85+t86+t87+t88;
t98 = -t93;
t103 = l_F_Y+r_F_Y+t102;
t106 = l_Tau_Alpha_Shoulder+r_Tau_Alpha_Shoulder+t57+t79+t80+t94+t96+t98+t99;
ddalpha_Body = t27.*t45.*t106.*1.2e+1-height_Body.*t2.*t4.*t27.*t45.*t104.*6.0+height_Body.*t4.*t6.*t27.*t45.*t103.*6.0;
if nargout > 1
    ddbeta_Body = ((t9.*(l_Tau_Alpha_Shoulder+r_Tau_Alpha_Shoulder)-l_F_Z.*t89+l_F_Y.*t92+r_F_Z.*t89-r_F_Y.*t92+t2.*t4.*t41-t4.*t6.*t40-(l_F_X.*t4.*t8.*width_Body)./2.0+(r_F_X.*t4.*t8.*width_Body)./2.0).*-1.2e+1)./(m_Body.*t14+m_Body.*t18);
end
if nargout > 2
    ddgamma_Body = t27.*t46.*t107.*1.2e+1+height_Body.*t4.*t27.*t46.*t74.*6.0+height_Body.*t2.*t9.*t27.*t46.*t103.*6.0+height_Body.*t6.*t9.*t27.*t46.*t104.*6.0;
end
if nargout > 3
    ddx_Head = t27.*t46.*t74.*(t33+t16.*t20.*3.0)+height_Body.*t4.*t27.*t46.*t107.*6.0+t2.*t4.*t9.*t16.*t27.*t46.*t103.*3.0+t4.*t6.*t9.*t16.*t27.*t46.*t104.*3.0;
end
if nargout > 4
    ddy_Head = t27.*t100.*t104.*t105.*-3.0+t27.*t100.*t103.*(t97+t17.*t19.*t22.*3.0+t17.*t20.*t21.*3.0+t19.*t22.*t29.*3.0+t20.*t21.*t32.*3.0)+height_Body.*t4.*t6.*t27.*t45.*t106.*6.0+height_Body.*t2.*t9.*t27.*t46.*t107.*6.0+t2.*t4.*t9.*t16.*t27.*t46.*t74.*3.0;
end
if nargout > 5
    ddz_Head = t27.*t100.*t103.*t105.*-3.0+t27.*t100.*t104.*(t97+t17.*t19.*t20.*3.0+t17.*t21.*t22.*3.0+t19.*t20.*t32.*3.0+t21.*t22.*t29.*3.0)-height_Body.*t2.*t4.*t27.*t45.*t106.*6.0+height_Body.*t6.*t9.*t27.*t46.*t107.*6.0+t4.*t6.*t9.*t16.*t27.*t46.*t74.*3.0;
end
