function [A11,A21,A31] = HFD_Coeffs_Ddl_Arm_Bottom_Constant(ddl_Beta_Hand,dl_Beta_Hand,dl_Alpha_Hand,g,l_Alpha_Hand,l_Beta_Hand,l_Tau_Alpha_Shoulder,length_Hand,m_Hand)
%HFD_COEFFS_DDL_ARM_BOTTOM_CONSTANT
%    [A11,A21,A31] = HFD_COEFFS_DDL_ARM_BOTTOM_CONSTANT(DDL_BETA_HAND,DL_BETA_HAND,DL_ALPHA_HAND,G,L_ALPHA_HAND,L_BETA_HAND,L_TAU_ALPHA_SHOULDER,LENGTH_HAND,M_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:36:58

t2 = cos(l_Alpha_Hand);
t3 = cos(l_Beta_Hand);
t4 = sin(l_Alpha_Hand);
t5 = sin(l_Beta_Hand);
t6 = dl_Beta_Hand.^2;
A11 = ddl_Beta_Hand.*length_Hand.*t3-length_Hand.*t5.*t6;
if nargout > 1
    t7 = dl_Alpha_Hand.^2;
    t8 = length_Hand.^2;
    t9 = t2.^2;
    t10 = t3.^2;
    t11 = t4.^2;
    t12 = m_Hand.*t8;
    t13 = (g.*length_Hand.*m_Hand.*t2.*t3)./2.0;
    t14 = t10.*t11.*t12.*3.0;
    t15 = t9.*t10.*t12.*3.0;
    t16 = (dl_Beta_Hand.*dl_Alpha_Hand.*t3.*t5.*t9.*t12)./2.0;
    t17 = (dl_Beta_Hand.*dl_Alpha_Hand.*t3.*t5.*t11.*t12)./2.0;
    t18 = -t16;
    t19 = -t17;
    t20 = t12+t14+t15;
    t21 = 1.0./t20;
    t22 = l_Tau_Alpha_Shoulder+t13+t18+t19;
    A21 = -ddl_Beta_Hand.*length_Hand.*t2.*t5-length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t21.*t22.*1.2e+1;
end
if nargout > 2
    A31 = -ddl_Beta_Hand.*length_Hand.*t4.*t5-length_Hand.*t3.*t4.*t6-length_Hand.*t3.*t4.*t7-dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t2.*t5.*2.0-length_Hand.*t2.*t3.*t21.*t22.*1.2e+1;
end
