function [ddth1,p1ddx,p1ddy] = find_Dds1(dth1,f2_X,f2_Y,g,l1,m1,tau2,th1)
%FIND_DDS1
%    [DDTH1,P1DDX,P1DDY] = FIND_DDS1(DTH1,F2_X,F2_Y,G,L1,M1,TAU2,TH1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Jun-2021 11:30:58

t2 = cos(th1);
t3 = sin(th1);
t4 = dth1.^2;
t5 = l1.^2;
t6 = t2.^2;
t7 = t3.^2;
t8 = f2_Y.*l1.*t2;
t9 = f2_X.*l1.*t3;
t10 = g.*l1.*m1.*t2;
t14 = (m1.*t5)./1.2e+1;
t11 = -t9;
t12 = (m1.*t6)./4.0;
t13 = (m1.*t7)./4.0;
t15 = t8+t10+t11+tau2;
t16 = t12+t13+t14;
t17 = 1.0./t16;
ddth1 = -t15.*t17;
if nargout > 1
    p1ddx = -l1.*t2.*t4+l1.*t3.*t15.*t17;
end
if nargout > 2
    p1ddy = -l1.*t3.*t4-l1.*t2.*t15.*t17;
end
