function [ddx2,ddy2,ddth2] = find_Dds2(dth2,f2_X,f2_Y,g,l2,m2,tau2,th2)
%FIND_DDS2
%    [DDX2,DDY2,DDTH2] = FIND_DDS2(DTH2,F2_X,F2_Y,G,L2,M2,TAU2,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Jun-2021 11:30:58

t2 = cos(th2);
t3 = sin(th2);
t4 = g.*m2;
t5 = dth2.^2;
t6 = l2.^2;
t8 = 1.0./m2;
t7 = 1.0./t6;
t9 = -t4;
t10 = l2.*t2.*t4;
t13 = (m2.*t2.*t5)./2.0;
t14 = (m2.*t3.*t5)./2.0;
t11 = l2.*t2.*t9;
t15 = f2_X+t13;
t16 = f2_Y+t9+t14;
t12 = t11+tau2;
ddx2 = t3.*t7.*t8.*t12.*6.0+t7.*t8.*t15.*(t6+t3.^2.*3.0)-t2.*t3.*t7.*t8.*t16.*3.0;
if nargout > 1
    ddy2 = t2.*t7.*t8.*t12.*-6.0+t7.*t8.*t16.*(t6+t2.^2.*3.0)-t2.*t3.*t7.*t8.*t15.*3.0;
end
if nargout > 2
    ddth2 = t7.*t8.*t12.*1.2e+1-t2.*t7.*t8.*t16.*6.0+t3.*t7.*t8.*t15.*6.0;
end
