function [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = FFD_Coeffs_Ddr_Arm_Bottom(dr_Beta_Hand,dr_Alpha_Hand,g,length_Hand,m_Hand,r_Alpha_Hand,r_Beta_Hand,r_Tau_Beta_Shoulder,r_Tau_Alpha_Shoulder)
%FFD_COEFFS_DDR_ARM_BOTTOM
%    [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = FFD_COEFFS_DDR_ARM_BOTTOM(DR_BETA_HAND,DR_ALPHA_HAND,G,LENGTH_HAND,M_HAND,R_ALPHA_HAND,R_BETA_HAND,R_TAU_BETA_SHOULDER,R_TAU_ALPHA_SHOULDER)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:11:22

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
t4 = sin(r_Alpha_Hand);
t5 = sin(r_Beta_Hand);
t6 = dr_Beta_Hand.^2;
t7 = dr_Alpha_Hand.^2;
t8 = length_Hand.^2;
t13 = 1.0./length_Hand;
t14 = 1.0./m_Hand;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t15 = m_Hand.*t8;
t21 = (g.*length_Hand.*m_Hand.*t2.*t3)./2.0;
t22 = (g.*length_Hand.*m_Hand.*t4.*t5)./2.0;
t16 = r_Tau_Beta_Shoulder.*t9;
t17 = r_Tau_Beta_Shoulder.*t11;
t18 = t9.*t10.*3.0;
t19 = t10.*t15.*3.0;
t20 = t10.*t11.*3.0;
t23 = -t22;
t24 = t9.*t12.*t15.*3.0;
t25 = t11.*t12.*t15.*3.0;
t26 = (t3.*t5.*t6.*t15)./4.0;
t28 = (dr_Beta_Hand.*dr_Alpha_Hand.*t3.*t5.*t9.*t15)./2.0;
t29 = (dr_Beta_Hand.*dr_Alpha_Hand.*t3.*t5.*t11.*t15)./2.0;
t31 = (t3.*t5.*t7.*t9.*t15)./4.0;
t34 = (t3.*t5.*t7.*t11.*t15)./4.0;
t27 = -t26;
t30 = t9.*t26;
t32 = -t28;
t33 = t11.*t26;
t35 = -t29;
t36 = t18+t20+1.0;
t39 = t15+t19+t24+t25;
t37 = 1.0./t36;
t40 = 1.0./t39;
A11 = t8.*t10.*t40.*-1.2e+1;
if nargout > 1
    t41 = r_Tau_Alpha_Shoulder+t21+t32+t35;
    t49 = t16+t17+t23+t27+t30+t31+t33+t34;
    t38 = t2.*t4.*t10.*t14.*t37.*1.2e+1;
    t42 = t2.*t3.*t5.*t8.*t40.*1.2e+1;
    t43 = t3.*t4.*t5.*t8.*t40.*1.2e+1;
    t46 = t2.*t4.*t8.*t12.*t40.*1.2e+1;
    t44 = -t42;
    A12 = t44;
end
if nargout > 2
    t45 = -t43;
    A13 = t45;
end
if nargout > 3
    A14 = length_Hand.*t5.*t6+length_Hand.*t3.*t40.*t49.*1.2e+1;
end
if nargout > 4
    A21 = t44;
end
if nargout > 5
    A22 = t8.*t9.*t12.*t40.*-1.2e+1-t10.*t11.*t14.*t37.*1.2e+1;
end
if nargout > 6
    t47 = -t46;
    t48 = t38+t47;
    A23 = t48;
end
if nargout > 7
    A24 = -length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t2.*t5.*t40.*t49.*1.2e+1+t3.*t4.*t13.*t14.*t37.*t41.*1.2e+1;
end
if nargout > 8
    A31 = t45;
end
if nargout > 9
    A32 = t48;
end
if nargout > 10
    A33 = t9.*t10.*t14.*t37.*-1.2e+1-t8.*t11.*t12.*t40.*1.2e+1;
end
if nargout > 11
    A34 = -length_Hand.*t3.*t4.*t6-length_Hand.*t3.*t4.*t7-dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t2.*t5.*2.0+length_Hand.*t4.*t5.*t40.*t49.*1.2e+1-t2.*t3.*t13.*t14.*t37.*t41.*1.2e+1;
end
