function ddr_Arm_Bottom = find_Ddr_Arm_Bottom_FRD(ddr_Beta_Hand,ddr_Alpha_Hand,dr_Beta_Hand,dr_Alpha_Hand,length_Hand,r_Alpha_Hand,r_Beta_Hand)
%FIND_DDR_ARM_BOTTOM_FRD
%    DDR_ARM_BOTTOM = FIND_DDR_ARM_BOTTOM_FRD(DDR_BETA_HAND,DDR_ALPHA_HAND,DR_BETA_HAND,DR_ALPHA_HAND,LENGTH_HAND,R_ALPHA_HAND,R_BETA_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 15:28:22

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
t4 = sin(r_Alpha_Hand);
t5 = sin(r_Beta_Hand);
t6 = dr_Beta_Hand.^2;
t7 = dr_Alpha_Hand.^2;
ddr_Arm_Bottom = [-ddr_Beta_Hand.*length_Hand.*t2.*t3+ddr_Alpha_Hand.*length_Hand.*t4.*t5+length_Hand.*t2.*t5.*t6+length_Hand.*t2.*t5.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t3.*t4.*2.0,-ddr_Beta_Hand.*length_Hand.*t2.*t5-ddr_Alpha_Hand.*length_Hand.*t3.*t4-length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t4.*t5.*2.0,ddr_Alpha_Hand.*length_Hand.*t2-length_Hand.*t4.*t7];
