function [A11,A12,A13,A14,A15,A16,A17,A21,A22,A23,A24,A25,A26,A27,A31,A32,A33,A34,A35,A36,A37] = find_Coeffs_Ddr_Shoulder_HFD(alpha_Body,beta_Body,dalpha_Body,dbeta_Body,ddbeta_Body,ddgamma_Body,depth_Body,dgamma_Body,g,gamma_Body,height_Body,l_Beta_Hand,l_F_X,l_F_Y,l_F_Z,l_Tau_Alpha_Shoulder,m_Body,r_Beta_Hand,r_F_X,r_F_Y,r_F_Z,r_Tau_Alpha_Shoulder,width_Body)
%FIND_COEFFS_DDR_SHOULDER_HFD
%    [A11,A12,A13,A14,A15,A16,A17,A21,A22,A23,A24,A25,A26,A27,A31,A32,A33,A34,A35,A36,A37] = FIND_COEFFS_DDR_SHOULDER_HFD(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DBETA_BODY,DDBETA_BODY,DDGAMMA_BODY,DEPTH_BODY,DGAMMA_BODY,G,GAMMA_BODY,HEIGHT_BODY,L_BETA_HAND,L_F_X,L_F_Y,L_F_Z,L_TAU_ALPHA_SHOULDER,M_BODY,R_BETA_HAND,R_F_X,R_F_Y,R_F_Z,R_TAU_ALPHA_SHOULDER,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 15:29:28

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = conj(l_Beta_Hand);
t6 = cos(l_Beta_Hand);
t7 = sin(alpha_Body);
t8 = conj(r_Beta_Hand);
t9 = cos(r_Beta_Hand);
t10 = sin(beta_Body);
t11 = sin(gamma_Body);
t13 = g.*m_Body;
t17 = dalpha_Body.^2;
t18 = dbeta_Body.^2;
t19 = depth_Body.^2;
t20 = dgamma_Body.^2;
t21 = height_Body.^2;
t22 = width_Body.^2;
t12 = cos(t5);
t14 = cos(t8);
t15 = sin(t5);
t16 = sin(t8);
t23 = t2.^2;
t24 = t4.^2;
t25 = t7.^2;
t26 = t11.^2;
t27 = l_Tau_Alpha_Shoulder.*t6;
t28 = r_Tau_Alpha_Shoulder.*t9;
t32 = -t13;
t34 = ddgamma_Body.*height_Body.*t4.*2.0;
t37 = dalpha_Body.*dbeta_Body.*t2.*t3.*width_Body;
t38 = dalpha_Body.*dbeta_Body.*t3.*t7.*width_Body;
t39 = dbeta_Body.*dgamma_Body.*t10.*t11.*width_Body;
t40 = height_Body.*t11.*t20.*2.0;
t41 = ddgamma_Body.*height_Body.*t2.*t11.*2.0;
t42 = dalpha_Body.*dgamma_Body.*height_Body.*t7.*t11.*4.0;
t43 = (t2.*t3.*width_Body)./2.0;
t44 = (t2.*t10.*width_Body)./2.0;
t45 = (t3.*t7.*width_Body)./2.0;
t46 = (t7.*t10.*width_Body)./2.0;
t47 = dalpha_Body.*dgamma_Body.*height_Body.*m_Body.*t2.*t11;
t48 = dalpha_Body.*dgamma_Body.*t3.*t4.*t7.*width_Body;
t49 = dbeta_Body.*dgamma_Body.*t2.*t4.*t10.*width_Body;
t50 = (ddbeta_Body.*m_Body.*t22)./1.2e+1;
t51 = (ddgamma_Body.*m_Body.*t22)./1.2e+1;
t52 = dalpha_Body.*dbeta_Body.*t2.*t10.*t11.*width_Body;
t53 = dbeta_Body.*dgamma_Body.*t4.*t7.*t10.*width_Body;
t54 = height_Body.*t2.*t4.*t17.*2.0;
t55 = height_Body.*t2.*t4.*t20.*2.0;
t56 = dalpha_Body.*dbeta_Body.*t7.*t10.*t11.*width_Body;
t60 = (ddbeta_Body.*t4.*t10.*width_Body)./2.0;
t61 = (ddgamma_Body.*t3.*t11.*width_Body)./2.0;
t62 = (l_F_X.*t3.*t11.*width_Body)./2.0;
t63 = (l_F_X.*t4.*t10.*width_Body)./2.0;
t64 = (r_F_X.*t3.*t11.*width_Body)./2.0;
t65 = (r_F_X.*t4.*t10.*width_Body)./2.0;
t66 = (ddbeta_Body.*m_Body.*t19)./1.2e+1;
t67 = dalpha_Body.*dgamma_Body.*t2.*t3.*t4.*width_Body;
t68 = (ddgamma_Body.*m_Body.*t21)./1.2e+1;
t69 = (height_Body.*t2.*t4.*t13)./2.0;
t71 = (ddgamma_Body.*height_Body.*m_Body.*t7.*t11)./2.0;
t72 = (height_Body.*t7.*t11.*t13)./2.0;
t77 = ddbeta_Body.*t2.*t3.*width_Body.*(-1.0./2.0);
t86 = (t3.*t4.*t18.*width_Body)./2.0;
t87 = (t3.*t4.*t20.*width_Body)./2.0;
t94 = t2.*t10.*t11.*width_Body.*(-1.0./2.0);
t95 = t3.*t7.*t11.*width_Body.*(-1.0./2.0);
t107 = t7.*t10.*t17.*width_Body.*(-1.0./2.0);
t108 = t7.*t10.*t18.*width_Body.*(-1.0./2.0);
t110 = (height_Body.*m_Body.*t4.*t7.*t17)./2.0;
t111 = (height_Body.*m_Body.*t4.*t7.*t20)./2.0;
t112 = r_F_Y.*t2.*t3.*t4.*width_Body.*(-1.0./2.0);
t113 = r_F_Z.*t3.*t4.*t7.*width_Body.*(-1.0./2.0);
t115 = ddbeta_Body.*t7.*t10.*t11.*width_Body.*(-1.0./2.0);
t123 = t2.*t3.*t11.*t17.*width_Body.*(-1.0./2.0);
t124 = t2.*t3.*t11.*t18.*width_Body.*(-1.0./2.0);
t125 = t2.*t3.*t11.*t20.*width_Body.*(-1.0./2.0);
t129 = (m_Body.*t4.*t11.*t20.*t21)./4.0;
t29 = r_Tau_Alpha_Shoulder.*t14;
t30 = l_Tau_Alpha_Shoulder.*t15;
t31 = r_Tau_Alpha_Shoulder.*t16;
t33 = l_Tau_Alpha_Shoulder.*t12;
t36 = -t34;
t57 = -t42;
t58 = ddbeta_Body.*t43;
t59 = ddbeta_Body.*t45;
t70 = t11.*t43;
t73 = t11.*t44;
t74 = t11.*t45;
t75 = t11.*t46;
t78 = -t60;
t79 = -t61;
t80 = -t62;
t81 = -t63;
t82 = -t48;
t83 = -t49;
t84 = -t52;
t85 = -t53;
t88 = -t69;
t89 = t17.*t44;
t90 = t18.*t44;
t91 = t17.*t46;
t92 = t18.*t46;
t93 = -t72;
t96 = ddgamma_Body.*t4.*t43;
t97 = l_F_Y.*t4.*t43;
t98 = r_F_Y.*t4.*t43;
t99 = ddgamma_Body.*t4.*t45;
t100 = l_F_Z.*t4.*t45;
t101 = r_F_Z.*t4.*t45;
t104 = (ddgamma_Body.*m_Body.*t21.*t24)./4.0;
t105 = -t86;
t106 = -t87;
t114 = ddbeta_Body.*t94;
t126 = t17.*t95;
t127 = t18.*t95;
t128 = t20.*t95;
t132 = -t129;
t133 = (ddgamma_Body.*m_Body.*t21.*t23.*t26)./4.0;
t134 = (ddgamma_Body.*m_Body.*t21.*t25.*t26)./4.0;
t135 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t11.*t21.*t23)./2.0;
t136 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t11.*t21.*t25)./2.0;
t139 = (m_Body.*t4.*t11.*t17.*t21.*t23)./4.0;
t140 = t23.*t129;
t141 = (m_Body.*t4.*t11.*t17.*t21.*t25)./4.0;
t142 = t25.*t129;
t145 = m_Body.*(t34-t40).*(-1.0./4.0);
t146 = t44+t95;
t147 = t45+t94;
t148 = (m_Body.*(t34-t40))./4.0;
t165 = l_F_Z+r_F_Z+t32+t47+t71+t110+t111;
t35 = -t31;
t76 = t29+t33;
t102 = ddbeta_Body.*t73;
t103 = ddbeta_Body.*t75;
t116 = t17.*t70;
t117 = t18.*t70;
t118 = t20.*t70;
t119 = t17.*t74;
t120 = t18.*t74;
t121 = t20.*t74;
t130 = t36+t40;
t143 = t43+t75;
t144 = t46+t70;
t153 = l_F_Y.*t146;
t154 = l_F_Y.*t147;
t155 = r_F_Y.*t146;
t156 = r_F_Y.*t147;
t157 = l_F_X+r_F_X+t148;
t162 = t41+t54+t55+t57;
t109 = t30+t35;
t122 = t11.*t76;
t149 = l_F_Z.*t143;
t150 = l_F_Z.*t144;
t151 = r_F_Z.*t143;
t152 = r_F_Z.*t144;
t160 = -t153;
t161 = -t156;
t163 = (m_Body.*t162)./4.0;
t131 = t7.*t109;
t137 = t2.*t4.*t109;
t158 = -t149;
t159 = -t150;
t164 = l_F_Y+r_F_Y+t163;
t138 = -t131;
t166 = t27+t28+t88+t135+t136+t152+t155+t159+t160;
t167 = t50+t65+t66+t81+t122+t137+t151+t154+t158+t161;
t168 = sign(t167);
t171 = t51+t64+t68+t80+t93+t97+t100+t104+t112+t113+t132+t133+t134+t138+t139+t140+t141+t142;
t169 = conj(t168);
t172 = sign(t171);
t170 = -t169;
t173 = conj(t172);
t174 = -t173;
t175 = t157.*Inf+t164.*Inf+t165.*Inf+t166.*Inf+t170.*Inf+t174.*Inf;
t176 = t44.*t175;
t177 = t46.*t175;
t178 = t70.*t175;
t179 = t74.*t175;
t180 = t95.*t175;
t181 = t39+t78+t79+t105+t106+t175;
A11 = t181;
if nargout > 1
    A12 = t181;
end
if nargout > 2
    A13 = t181;
end
if nargout > 3
    A14 = t181;
end
if nargout > 4
    A15 = t181;
end
if nargout > 5
    A16 = t181;
end
if nargout > 6
    A17 = t181;
end
if nargout > 7
    t182 = t38+t67+t77+t84+t85+t89+t90+t99+t115+t126+t127+t128+t175+t177+t178;
    t183 = t37+t56+t59+t82+t83+t96+t107+t108+t114+t123+t124+t125+t175+t176+t180;
    A21 = t183;
end
if nargout > 8
    A22 = t183;
end
if nargout > 9
    A23 = t183;
end
if nargout > 10
    A24 = t183;
end
if nargout > 11
    A25 = t183;
end
if nargout > 12
    A26 = t183;
end
if nargout > 13
    A27 = t183;
end
if nargout > 14
    A31 = t182;
end
if nargout > 15
    A32 = t182;
end
if nargout > 16
    A33 = t182;
end
if nargout > 17
    A34 = t182;
end
if nargout > 18
    A35 = t182;
end
if nargout > 19
    A36 = t182;
end
if nargout > 20
    A37 = t182;
end
