function [ddalpha_Body,ddbeta_Body,ddgamma_Body,ddx_Head,ddy_Head,ddz_Head] = find_Dds_Body_FFD(alpha_Body,beta_Body,dalpha_Body,depth_Body,dgamma_Body,g,gamma_Body,height_Body,l_Beta_Hand,l_F_X,l_F_Y,l_F_Z,l_Tau_Beta_Shoulder,l_Tau_Alpha_Shoulder,m_Body,r_Beta_Hand,r_F_X,r_F_Y,r_F_Z,r_Tau_Beta_Shoulder,r_Tau_Alpha_Shoulder,width_Body)
%FIND_DDS_BODY_FFD
%    [DDALPHA_BODY,DDBETA_BODY,DDGAMMA_BODY,DDX_HEAD,DDY_HEAD,DDZ_HEAD] = FIND_DDS_BODY_FFD(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DEPTH_BODY,DGAMMA_BODY,G,GAMMA_BODY,HEIGHT_BODY,L_BETA_HAND,L_F_X,L_F_Y,L_F_Z,L_TAU_BETA_SHOULDER,L_TAU_ALPHA_SHOULDER,M_BODY,R_BETA_HAND,R_F_X,R_F_Y,R_F_Z,R_TAU_BETA_SHOULDER,R_TAU_ALPHA_SHOULDER,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 15:28:36

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = conj(l_Beta_Hand);
t6 = sin(alpha_Body);
t7 = conj(r_Beta_Hand);
t8 = sin(beta_Body);
t9 = sin(gamma_Body);
t11 = g.*m_Body;
t13 = l_Tau_Beta_Shoulder+r_Tau_Beta_Shoulder;
t16 = dalpha_Body.^2;
t17 = depth_Body.^2;
t18 = dgamma_Body.^2;
t19 = height_Body.^2;
t21 = width_Body.^2;
t26 = 1.0./m_Body;
t10 = cos(t5);
t12 = cos(t7);
t14 = sin(t5);
t15 = sin(t7);
t20 = t19.^2;
t22 = t2.^2;
t23 = t4.^2;
t24 = t6.^2;
t25 = t9.^2;
t30 = -t11;
t32 = t2.*t13;
t34 = t17.*t19;
t35 = t17+t19;
t36 = t17.*t21;
t37 = t19.*t21;
t38 = t19+t21;
t39 = dalpha_Body.*dgamma_Body.*height_Body.*t6.*t9.*4.0;
t40 = (t2.*t3.*width_Body)./2.0;
t41 = (t2.*t8.*width_Body)./2.0;
t42 = (t3.*t6.*width_Body)./2.0;
t43 = (t6.*t8.*width_Body)./2.0;
t44 = dalpha_Body.*dgamma_Body.*height_Body.*m_Body.*t2.*t9;
t45 = height_Body.*t2.*t4.*t16.*2.0;
t46 = height_Body.*t2.*t4.*t18.*2.0;
t50 = (l_F_X.*t3.*t9.*width_Body)./2.0;
t51 = (r_F_X.*t3.*t9.*width_Body)./2.0;
t52 = (height_Body.*t2.*t4.*t11)./2.0;
t54 = (height_Body.*t6.*t9.*t11)./2.0;
t58 = (height_Body.*m_Body.*t9.*t18)./2.0;
t61 = t2.*t8.*t9.*width_Body.*(-1.0./2.0);
t62 = t3.*t6.*t9.*width_Body.*(-1.0./2.0);
t71 = (height_Body.*m_Body.*t4.*t6.*t16)./2.0;
t72 = (height_Body.*m_Body.*t4.*t6.*t18)./2.0;
t73 = l_F_Y.*t2.*t3.*t4.*width_Body.*(-1.0./2.0);
t74 = l_F_Z.*t3.*t4.*t6.*width_Body.*(-1.0./2.0);
t79 = (m_Body.*t4.*t9.*t18.*t19)./4.0;
t27 = r_Tau_Alpha_Shoulder.*t12;
t28 = l_Tau_Alpha_Shoulder.*t14;
t29 = r_Tau_Alpha_Shoulder.*t15;
t31 = l_Tau_Alpha_Shoulder.*t10;
t47 = -t39;
t48 = 1.0./t35;
t49 = 1.0./t38;
t53 = t9.*t40;
t55 = t9.*t41;
t56 = t9.*t42;
t57 = t9.*t43;
t59 = -t51;
t60 = -t52;
t63 = l_F_Y.*t4.*t40;
t64 = r_F_Y.*t4.*t40;
t65 = l_F_Z.*t4.*t42;
t66 = r_F_Z.*t4.*t42;
t67 = -t58;
t68 = t2.*t6.*t20.*t23;
t69 = t2.*t6.*t20.*t25;
t77 = t2.*t6.*t25.*t34;
t78 = t2.*t6.*t23.*t37;
t82 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t9.*t19.*t22)./2.0;
t83 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t9.*t19.*t24)./2.0;
t84 = (m_Body.*t4.*t9.*t16.*t19.*t22)./4.0;
t85 = t22.*t79;
t86 = (m_Body.*t4.*t9.*t16.*t19.*t24)./4.0;
t87 = t24.*t79;
t89 = m_Body.*t4.*t9.*t18.*t19.*t22.*(-1.0./4.0);
t91 = m_Body.*t4.*t9.*t18.*t19.*t24.*(-1.0./4.0);
t94 = t41+t62;
t95 = t42+t61;
t100 = t20+t34+t36+t37;
t107 = l_F_Z+r_F_Z+t30+t44+t71+t72;
t33 = -t29;
t75 = -t69;
t76 = l_F_X+r_F_X+t67;
t81 = -t77;
t88 = -t84;
t90 = -t86;
t92 = t40+t57;
t93 = t43+t53;
t98 = l_F_Y.*t94;
t99 = r_F_Y.*t94;
t103 = 1.0./t100;
t104 = t45+t46+t47;
t70 = t28+t33;
t96 = l_F_Z.*t93;
t97 = r_F_Z.*t93;
t102 = -t98;
t105 = (m_Body.*t104)./4.0;
t108 = t68+t75+t78+t81;
t80 = t6.*t70;
t101 = -t96;
t106 = l_F_Y+r_F_Y+t105;
t109 = t27+t31+t60+t82+t83+t97+t99+t101+t102;
ddalpha_Body = t26.*t48.*t109.*1.2e+1-height_Body.*t2.*t4.*t26.*t48.*t107.*6.0+height_Body.*t4.*t6.*t26.*t48.*t106.*6.0;
if nargout > 1
    ddbeta_Body = ((t9.*(t27+t31)-l_F_Z.*t92+l_F_Y.*t95+r_F_Z.*t92-r_F_Y.*t95-t4.*t6.*t13+t2.*t4.*t70-(l_F_X.*t4.*t8.*width_Body)./2.0+(r_F_X.*t4.*t8.*width_Body)./2.0).*-1.2e+1)./(m_Body.*t17+m_Body.*t21);
end
if nargout > 2
    t110 = t32+t50+t54+t59+t64+t66+t73+t74+t79+t80+t88+t89+t90+t91;
    ddgamma_Body = t26.*t49.*t110.*1.2e+1+height_Body.*t4.*t26.*t49.*t76.*6.0+height_Body.*t2.*t9.*t26.*t49.*t106.*6.0+height_Body.*t6.*t9.*t26.*t49.*t107.*6.0;
end
if nargout > 3
    ddx_Head = t26.*t49.*t76.*(t38+t19.*t23.*3.0)+height_Body.*t4.*t26.*t49.*t110.*6.0+t2.*t4.*t9.*t19.*t26.*t49.*t106.*3.0+t4.*t6.*t9.*t19.*t26.*t49.*t107.*3.0;
end
if nargout > 4
    ddy_Head = t26.*t103.*t107.*t108.*-3.0+t26.*t103.*t106.*(t100+t20.*t22.*t25.*3.0+t20.*t23.*t24.*3.0+t22.*t25.*t34.*3.0+t23.*t24.*t37.*3.0)+height_Body.*t4.*t6.*t26.*t48.*t109.*6.0+height_Body.*t2.*t9.*t26.*t49.*t110.*6.0+t2.*t4.*t9.*t19.*t26.*t49.*t76.*3.0;
end
if nargout > 5
    ddz_Head = t26.*t103.*t106.*t108.*-3.0+t26.*t103.*t107.*(t100+t20.*t22.*t23.*3.0+t20.*t24.*t25.*3.0+t22.*t23.*t37.*3.0+t24.*t25.*t34.*3.0)-height_Body.*t2.*t4.*t26.*t48.*t109.*6.0+height_Body.*t6.*t9.*t26.*t49.*t110.*6.0+t4.*t6.*t9.*t19.*t26.*t49.*t76.*3.0;
end
