function [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = find_Coeffs_Ddr_Arm_Bottom(dr_Beta_Hand,dr_Alpha_Hand,g,length_Hand,m_Hand,r_Alpha_Hand,r_Beta_Hand,r_Tau_Beta_Shoulder,r_Tau_Alpha_Shoulder)
%FIND_COEFFS_DDR_ARM_BOTTOM
%    [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = FIND_COEFFS_DDR_ARM_BOTTOM(DR_BETA_HAND,DR_ALPHA_HAND,G,LENGTH_HAND,M_HAND,R_ALPHA_HAND,R_BETA_HAND,R_TAU_BETA_SHOULDER,R_TAU_ALPHA_SHOULDER)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 12:14:47

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
t4 = sin(r_Alpha_Hand);
t5 = sin(r_Beta_Hand);
t6 = dr_Beta_Hand.^2;
t7 = dr_Alpha_Hand.^2;
t8 = length_Hand.^2;
t13 = 1.0./length_Hand;
t14 = 1.0./m_Hand;
t15 = -r_Tau_Beta_Shoulder;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t16 = m_Hand.*t8;
t17 = (g.*length_Hand.*m_Hand.*t2)./2.0;
t18 = t9.*t10.*3.0;
t19 = t9.*t16.*3.0;
t20 = t9.*t12.*3.0;
t21 = t10.*t11.*t16.*3.0;
t22 = t11.*t12.*t16.*3.0;
t23 = (t2.*t4.*t7.*t16)./4.0;
t25 = (dr_Beta_Hand.*dr_Alpha_Hand.*t2.*t4.*t10.*t16)./2.0;
t26 = (dr_Beta_Hand.*dr_Alpha_Hand.*t2.*t4.*t12.*t16)./2.0;
t27 = (t2.*t4.*t6.*t10.*t16)./4.0;
t29 = (t2.*t4.*t6.*t12.*t16)./4.0;
t24 = -t23;
t28 = t10.*t23;
t30 = t12.*t23;
t31 = t18+t20+1.0;
t35 = t15+t25+t26;
t36 = t16+t19+t21+t22;
t32 = 1.0./t31;
t37 = 1.0./t36;
A11 = t9.*t10.*t14.*t32.*-1.2e+1-t8.*t11.*t12.*t37.*1.2e+1;
if nargout > 1
    t43 = r_Tau_Alpha_Shoulder+t17+t24+t27+t28+t29+t30;
    t33 = t3.*t5.*t9.*t14.*t32.*1.2e+1;
    t38 = t2.*t3.*t4.*t8.*t37.*1.2e+1;
    t39 = t2.*t4.*t5.*t8.*t37.*1.2e+1;
    t41 = t3.*t5.*t8.*t11.*t37.*1.2e+1;
    t34 = -t33;
    t40 = -t39;
    t42 = t34+t41;
    A12 = t42;
end
if nargout > 2
    A13 = t40;
end
if nargout > 3
    A14 = length_Hand.*t2.*t5.*t6+length_Hand.*t2.*t5.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t3.*t4.*2.0-length_Hand.*t4.*t5.*t37.*t43.*1.2e+1-t2.*t3.*t13.*t14.*t32.*t35.*1.2e+1;
end
if nargout > 4
    A21 = t42;
end
if nargout > 5
    A22 = t8.*t10.*t11.*t37.*-1.2e+1-t9.*t12.*t14.*t32.*1.2e+1;
end
if nargout > 6
    A23 = t38;
end
if nargout > 7
    A24 = -length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t37.*t43.*1.2e+1-t2.*t5.*t13.*t14.*t32.*t35.*1.2e+1;
end
if nargout > 8
    A31 = t40;
end
if nargout > 9
    A32 = t38;
end
if nargout > 10
    A33 = t8.*t9.*t37.*-1.2e+1;
end
if nargout > 11
    A34 = -length_Hand.*t4.*t7-length_Hand.*t2.*t37.*t43.*1.2e+1;
end
