function [A11,A12,A13,A14,A15,A16,A17,A21,A22,A23,A24,A25,A26,A27,A31,A32,A33,A34,A35,A36,A37] = find_Coeffs_Ddl_Shoulder_HFD(alpha_Body,beta_Body,dalpha_Body,dbeta_Body,ddbeta_Body,ddgamma_Body,depth_Body,dgamma_Body,g,gamma_Body,height_Body,l_Beta_Hand,l_F_X,l_F_Y,l_F_Z,l_Tau_Alpha_Shoulder,m_Body,r_Beta_Hand,r_F_X,r_F_Y,r_F_Z,r_Tau_Alpha_Shoulder,width_Body)
%FIND_COEFFS_DDL_SHOULDER_HFD
%    [A11,A12,A13,A14,A15,A16,A17,A21,A22,A23,A24,A25,A26,A27,A31,A32,A33,A34,A35,A36,A37] = FIND_COEFFS_DDL_SHOULDER_HFD(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DBETA_BODY,DDBETA_BODY,DDGAMMA_BODY,DEPTH_BODY,DGAMMA_BODY,G,GAMMA_BODY,HEIGHT_BODY,L_BETA_HAND,L_F_X,L_F_Y,L_F_Z,L_TAU_ALPHA_SHOULDER,M_BODY,R_BETA_HAND,R_F_X,R_F_Y,R_F_Z,R_TAU_ALPHA_SHOULDER,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 15:29:30

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = conj(l_Beta_Hand);
t6 = cos(l_Beta_Hand);
t7 = sin(alpha_Body);
t8 = conj(r_Beta_Hand);
t9 = cos(r_Beta_Hand);
t10 = sin(beta_Body);
t11 = sin(gamma_Body);
t13 = g.*m_Body;
t17 = dalpha_Body.^2;
t18 = dbeta_Body.^2;
t19 = depth_Body.^2;
t20 = dgamma_Body.^2;
t21 = height_Body.^2;
t22 = width_Body.^2;
t12 = cos(t5);
t14 = cos(t8);
t15 = sin(t5);
t16 = sin(t8);
t23 = t2.^2;
t24 = t4.^2;
t25 = t7.^2;
t26 = t11.^2;
t27 = l_Tau_Alpha_Shoulder.*t6;
t28 = r_Tau_Alpha_Shoulder.*t9;
t32 = -t13;
t34 = ddgamma_Body.*height_Body.*t4.*2.0;
t37 = dalpha_Body.*dbeta_Body.*t2.*t3.*width_Body;
t38 = dalpha_Body.*dbeta_Body.*t3.*t7.*width_Body;
t39 = dbeta_Body.*dgamma_Body.*t10.*t11.*width_Body;
t40 = height_Body.*t11.*t20.*2.0;
t41 = ddgamma_Body.*height_Body.*t2.*t11.*2.0;
t42 = dalpha_Body.*dgamma_Body.*height_Body.*t7.*t11.*4.0;
t43 = (t2.*t3.*width_Body)./2.0;
t44 = (t2.*t10.*width_Body)./2.0;
t45 = (t3.*t7.*width_Body)./2.0;
t46 = (t7.*t10.*width_Body)./2.0;
t47 = dalpha_Body.*dgamma_Body.*height_Body.*m_Body.*t2.*t11;
t48 = dalpha_Body.*dgamma_Body.*t3.*t4.*t7.*width_Body;
t49 = dbeta_Body.*dgamma_Body.*t2.*t4.*t10.*width_Body;
t50 = (ddbeta_Body.*m_Body.*t22)./1.2e+1;
t51 = (ddgamma_Body.*m_Body.*t22)./1.2e+1;
t52 = dalpha_Body.*dbeta_Body.*t2.*t10.*t11.*width_Body;
t53 = dbeta_Body.*dgamma_Body.*t4.*t7.*t10.*width_Body;
t54 = height_Body.*t2.*t4.*t17.*2.0;
t55 = height_Body.*t2.*t4.*t20.*2.0;
t56 = dalpha_Body.*dbeta_Body.*t7.*t10.*t11.*width_Body;
t63 = (ddbeta_Body.*t4.*t10.*width_Body)./2.0;
t64 = (ddgamma_Body.*t3.*t11.*width_Body)./2.0;
t65 = (l_F_X.*t3.*t11.*width_Body)./2.0;
t66 = (l_F_X.*t4.*t10.*width_Body)./2.0;
t67 = (r_F_X.*t3.*t11.*width_Body)./2.0;
t68 = (r_F_X.*t4.*t10.*width_Body)./2.0;
t69 = (ddbeta_Body.*m_Body.*t19)./1.2e+1;
t70 = dalpha_Body.*dgamma_Body.*t2.*t3.*t4.*width_Body;
t71 = (ddgamma_Body.*m_Body.*t21)./1.2e+1;
t72 = (height_Body.*t2.*t4.*t13)./2.0;
t74 = (ddgamma_Body.*height_Body.*m_Body.*t7.*t11)./2.0;
t75 = (height_Body.*t7.*t11.*t13)./2.0;
t80 = ddbeta_Body.*t3.*t7.*width_Body.*(-1.0./2.0);
t84 = (t3.*t4.*t18.*width_Body)./2.0;
t85 = (t3.*t4.*t20.*width_Body)./2.0;
t92 = t2.*t10.*t11.*width_Body.*(-1.0./2.0);
t93 = t3.*t7.*t11.*width_Body.*(-1.0./2.0);
t104 = t2.*t10.*t17.*width_Body.*(-1.0./2.0);
t105 = t2.*t10.*t18.*width_Body.*(-1.0./2.0);
t107 = ddgamma_Body.*t2.*t3.*t4.*width_Body.*(-1.0./2.0);
t108 = (height_Body.*m_Body.*t4.*t7.*t17)./2.0;
t109 = (height_Body.*m_Body.*t4.*t7.*t20)./2.0;
t110 = r_F_Y.*t2.*t3.*t4.*width_Body.*(-1.0./2.0);
t111 = ddgamma_Body.*t3.*t4.*t7.*width_Body.*(-1.0./2.0);
t112 = r_F_Z.*t3.*t4.*t7.*width_Body.*(-1.0./2.0);
t120 = (m_Body.*t4.*t11.*t20.*t21)./4.0;
t29 = r_Tau_Alpha_Shoulder.*t14;
t30 = l_Tau_Alpha_Shoulder.*t15;
t31 = r_Tau_Alpha_Shoulder.*t16;
t33 = l_Tau_Alpha_Shoulder.*t12;
t36 = -t34;
t57 = -t37;
t58 = -t38;
t59 = -t42;
t60 = -t39;
t61 = ddbeta_Body.*t43;
t62 = ddbeta_Body.*t45;
t73 = t11.*t43;
t76 = t11.*t44;
t77 = t11.*t45;
t78 = t11.*t46;
t81 = -t65;
t82 = -t66;
t83 = -t56;
t86 = -t72;
t87 = t17.*t44;
t88 = t18.*t44;
t89 = t17.*t46;
t90 = t18.*t46;
t91 = -t75;
t94 = ddgamma_Body.*t4.*t43;
t95 = l_F_Y.*t4.*t43;
t96 = r_F_Y.*t4.*t43;
t97 = ddgamma_Body.*t4.*t45;
t98 = l_F_Z.*t4.*t45;
t99 = r_F_Z.*t4.*t45;
t102 = -t70;
t103 = (ddgamma_Body.*m_Body.*t21.*t24)./4.0;
t123 = -t120;
t124 = (ddgamma_Body.*m_Body.*t21.*t23.*t26)./4.0;
t125 = (ddgamma_Body.*m_Body.*t21.*t25.*t26)./4.0;
t126 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t11.*t21.*t23)./2.0;
t127 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t11.*t21.*t25)./2.0;
t130 = (m_Body.*t4.*t11.*t17.*t21.*t23)./4.0;
t131 = t23.*t120;
t132 = (m_Body.*t4.*t11.*t17.*t21.*t25)./4.0;
t133 = t25.*t120;
t136 = m_Body.*(t34-t40).*(-1.0./4.0);
t137 = t44+t93;
t138 = t45+t92;
t139 = (m_Body.*(t34-t40))./4.0;
t156 = l_F_Z+r_F_Z+t32+t47+t74+t108+t109;
t35 = -t31;
t79 = t29+t33;
t100 = ddbeta_Body.*t76;
t101 = ddbeta_Body.*t78;
t113 = t17.*t73;
t114 = t18.*t73;
t115 = t20.*t73;
t116 = t17.*t77;
t117 = t18.*t77;
t118 = t20.*t77;
t121 = t36+t40;
t134 = t43+t78;
t135 = t46+t73;
t144 = l_F_Y.*t137;
t145 = l_F_Y.*t138;
t146 = r_F_Y.*t137;
t147 = r_F_Y.*t138;
t148 = l_F_X+r_F_X+t139;
t153 = t41+t54+t55+t59;
t106 = t30+t35;
t119 = t11.*t79;
t140 = l_F_Z.*t134;
t141 = l_F_Z.*t135;
t142 = r_F_Z.*t134;
t143 = r_F_Z.*t135;
t151 = -t144;
t152 = -t147;
t154 = (m_Body.*t153)./4.0;
t122 = t7.*t106;
t128 = t2.*t4.*t106;
t149 = -t140;
t150 = -t141;
t155 = l_F_Y+r_F_Y+t154;
t129 = -t122;
t157 = t27+t28+t86+t126+t127+t143+t146+t150+t151;
t158 = t50+t68+t69+t82+t119+t128+t142+t145+t149+t152;
t159 = sign(t158);
t162 = t51+t67+t71+t81+t91+t95+t98+t103+t110+t112+t123+t124+t125+t129+t130+t131+t132+t133;
t160 = conj(t159);
t163 = sign(t162);
t161 = -t160;
t164 = conj(t163);
t165 = -t164;
t166 = t148.*Inf+t155.*Inf+t156.*Inf+t157.*Inf+t161.*Inf+t165.*Inf;
t167 = t44.*t166;
t168 = t46.*t166;
t169 = t2.*t10.*t166.*width_Body.*(-1.0./2.0);
t170 = t7.*t10.*t166.*width_Body.*(-1.0./2.0);
t171 = t73.*t166;
t172 = t77.*t166;
t173 = t2.*t3.*t11.*t166.*width_Body.*(-1.0./2.0);
t174 = t60+t63+t64+t84+t85+t166;
A11 = t174;
if nargout > 1
    A12 = t174;
end
if nargout > 2
    A13 = t174;
end
if nargout > 3
    A14 = t174;
end
if nargout > 4
    A15 = t174;
end
if nargout > 5
    A16 = t174;
end
if nargout > 6
    A17 = t174;
end
if nargout > 7
    t175 = t48+t49+t57+t80+t83+t89+t90+t100+t107+t113+t114+t115+t166+t169+t172;
    A21 = t175;
end
if nargout > 8
    A22 = t175;
end
if nargout > 9
    A23 = t175;
end
if nargout > 10
    A24 = t175;
end
if nargout > 11
    A25 = t175;
end
if nargout > 12
    A26 = t175;
end
if nargout > 13
    A27 = t175;
end
if nargout > 14
    t176 = t52+t53+t58+t61+t101+t102+t104+t105+t111+t116+t117+t118+t166+t170+t173;
    A31 = t176;
end
if nargout > 15
    A32 = t176;
end
if nargout > 16
    A33 = t176;
end
if nargout > 17
    A34 = t176;
end
if nargout > 18
    A35 = t176;
end
if nargout > 19
    A36 = t176;
end
if nargout > 20
    A37 = t176;
end
