function [ddalpha_Body,ddbeta_Body,ddgamma_Body,ddx_Head,ddy_Head,ddz_Head] = find_Dds_Body(alpha_Body,beta_Body,dalpha_Body,depth_Body,dgamma_Body,g,gamma_Body,height_Body,l_F_X,l_F_Y,l_F_Z,l_Tau_Alpha_Shoulder,m_Body,r_F_X,r_F_Y,r_F_Z,r_Tau_Alpha_Shoulder,width_Body)
%FIND_DDS_BODY
%    [DDALPHA_BODY,DDBETA_BODY,DDGAMMA_BODY,DDX_HEAD,DDY_HEAD,DDZ_HEAD] = FIND_DDS_BODY(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DEPTH_BODY,DGAMMA_BODY,G,GAMMA_BODY,HEIGHT_BODY,L_F_X,L_F_Y,L_F_Z,L_TAU_ALPHA_SHOULDER,M_BODY,R_F_X,R_F_Y,R_F_Z,R_TAU_ALPHA_SHOULDER,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Jun-2021 23:36:40

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = sin(beta_Body);
t7 = sin(gamma_Body);
t8 = g.*m_Body;
t9 = dalpha_Body.^2;
t10 = depth_Body.^2;
t11 = dgamma_Body.^2;
t12 = height_Body.^2;
t14 = width_Body.^2;
t19 = 1.0./m_Body;
t13 = t12.^2;
t15 = t2.^2;
t16 = t4.^2;
t17 = t5.^2;
t18 = t7.^2;
t20 = t5.*t6;
t21 = -t8;
t22 = t2.*t3;
t23 = t2.*t6;
t24 = t3.*t5;
t29 = t10.*t12;
t30 = t10+t12;
t31 = t10.*t14;
t32 = t12.*t14;
t33 = t12+t14;
t34 = dalpha_Body.*dgamma_Body.*height_Body.*t5.*t7.*4.0;
t35 = dalpha_Body.*dgamma_Body.*height_Body.*m_Body.*t2.*t7;
t38 = height_Body.*t2.*t4.*t9.*2.0;
t39 = height_Body.*t2.*t4.*t11.*2.0;
t43 = (l_F_X.*t3.*t7.*width_Body)./2.0;
t44 = (r_F_X.*t3.*t7.*width_Body)./2.0;
t45 = (height_Body.*t2.*t4.*t8)./2.0;
t46 = (height_Body.*t5.*t7.*t8)./2.0;
t47 = (height_Body.*m_Body.*t7.*t11)./2.0;
t60 = (height_Body.*m_Body.*t4.*t5.*t9)./2.0;
t61 = (height_Body.*m_Body.*t4.*t5.*t11)./2.0;
t70 = (m_Body.*t4.*t7.*t11.*t12)./4.0;
t25 = t7.*t22;
t26 = t7.*t23;
t27 = t7.*t24;
t28 = t7.*t20;
t40 = -t34;
t41 = 1.0./t30;
t42 = 1.0./t33;
t48 = -t43;
t49 = -t45;
t50 = -t46;
t51 = (l_F_Y.*t4.*t22.*width_Body)./2.0;
t52 = (r_F_Y.*t4.*t22.*width_Body)./2.0;
t53 = (l_F_Z.*t4.*t24.*width_Body)./2.0;
t54 = (r_F_Z.*t4.*t24.*width_Body)./2.0;
t55 = -t47;
t56 = t2.*t5.*t13.*t16;
t57 = t2.*t5.*t13.*t18;
t68 = t2.*t5.*t18.*t29;
t69 = t2.*t5.*t16.*t32;
t71 = -t70;
t73 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t7.*t12.*t15)./2.0;
t74 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t7.*t12.*t17)./2.0;
t75 = (m_Body.*t4.*t7.*t9.*t12.*t15)./4.0;
t76 = t15.*t70;
t77 = (m_Body.*t4.*t7.*t9.*t12.*t17)./4.0;
t78 = t17.*t70;
t85 = t13+t29+t31+t32;
t90 = l_F_Z+r_F_Z+t21+t35+t60+t61;
t36 = -t26;
t37 = -t27;
t58 = t20+t25;
t59 = t22+t28;
t62 = -t52;
t63 = -t54;
t64 = -t57;
t65 = l_F_X+r_F_X+t55;
t72 = -t68;
t86 = 1.0./t85;
t87 = t38+t39+t40;
t66 = t23+t37;
t67 = t24+t36;
t79 = (l_F_Z.*t58.*width_Body)./2.0;
t80 = (r_F_Z.*t58.*width_Body)./2.0;
t88 = (m_Body.*t87)./4.0;
t91 = t56+t64+t69+t72;
t93 = t44+t48+t50+t51+t53+t62+t63+t71+t75+t76+t77+t78;
t81 = -t79;
t82 = (l_F_Y.*t66.*width_Body)./2.0;
t83 = (r_F_Y.*t66.*width_Body)./2.0;
t89 = l_F_Y+r_F_Y+t88;
t84 = -t82;
t92 = l_Tau_Alpha_Shoulder+r_Tau_Alpha_Shoulder+t49+t73+t74+t80+t81+t83+t84;
ddalpha_Body = t19.*t41.*t92.*1.2e+1-height_Body.*t2.*t4.*t19.*t41.*t90.*6.0+height_Body.*t4.*t5.*t19.*t41.*t89.*6.0;
if nargout > 1
    ddbeta_Body = (((l_F_Z.*t59.*width_Body)./2.0-(l_F_Y.*t67.*width_Body)./2.0-(r_F_Z.*t59.*width_Body)./2.0+(r_F_Y.*t67.*width_Body)./2.0+(l_F_X.*t4.*t6.*width_Body)./2.0-(r_F_X.*t4.*t6.*width_Body)./2.0).*1.2e+1)./(m_Body.*t10+m_Body.*t14);
end
if nargout > 2
    ddgamma_Body = t19.*t42.*t93.*-1.2e+1+height_Body.*t4.*t19.*t42.*t65.*6.0+height_Body.*t2.*t7.*t19.*t42.*t89.*6.0+height_Body.*t5.*t7.*t19.*t42.*t90.*6.0;
end
if nargout > 3
    ddx_Head = t19.*t42.*t65.*(t33+t12.*t16.*3.0)-height_Body.*t4.*t19.*t42.*t93.*6.0+t2.*t4.*t7.*t12.*t19.*t42.*t89.*3.0+t4.*t5.*t7.*t12.*t19.*t42.*t90.*3.0;
end
if nargout > 4
    ddy_Head = t19.*t86.*t90.*t91.*-3.0+t19.*t86.*t89.*(t85+t13.*t15.*t18.*3.0+t13.*t16.*t17.*3.0+t15.*t18.*t29.*3.0+t16.*t17.*t32.*3.0)+height_Body.*t4.*t5.*t19.*t41.*t92.*6.0-height_Body.*t2.*t7.*t19.*t42.*t93.*6.0+t2.*t4.*t7.*t12.*t19.*t42.*t65.*3.0;
end
if nargout > 5
    ddz_Head = t19.*t86.*t89.*t91.*-3.0+t19.*t86.*t90.*(t85+t13.*t15.*t16.*3.0+t13.*t17.*t18.*3.0+t15.*t16.*t32.*3.0+t17.*t18.*t29.*3.0)-height_Body.*t2.*t4.*t19.*t41.*t92.*6.0-height_Body.*t5.*t7.*t19.*t42.*t93.*6.0+t4.*t5.*t7.*t12.*t19.*t42.*t65.*3.0;
end
