function r_Hip = find_R_Hip_FRD(alpha_Body,beta_Body,gamma_Body,height_Body,width_Body,x_Head,y_Head,z_Head)
%FIND_R_HIP_FRD
%    R_HIP = FIND_R_HIP_FRD(ALPHA_BODY,BETA_BODY,GAMMA_BODY,HEIGHT_BODY,WIDTH_BODY,X_HEAD,Y_HEAD,Z_HEAD)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 15:28:46

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = sin(beta_Body);
t7 = sin(gamma_Body);
t8 = height_Body.*t4;
t9 = (t3.*t7.*width_Body)./2.0;
t10 = t8+t9;
r_Hip = [x_Head-height_Body.*t7+(t3.*t4.*width_Body)./2.0,y_Head+t2.*t10+(t5.*t6.*width_Body)./2.0,z_Head+t5.*t10-(t2.*t6.*width_Body)./2.0];
