function [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = find_Coeffs_Ddr_Arlpha_Tau_Beta_Arm_R(ddr_Beta_Hand,dr_Beta_Hand,dr_Alpha_Hand,g,length_Hand,m_Hand,r_Alpha_Hand,r_Beta_Hand,r_Tau_Alpha_Shoulder)
%FIND_COEFFS_DDR_ARLPHA_TAU_BETA_ARM_R
%    [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = FIND_COEFFS_DDR_ARLPHA_TAU_BETA_ARM_R(DDR_BETA_HAND,DR_BETA_HAND,DR_ALPHA_HAND,G,LENGTH_HAND,M_HAND,R_ALPHA_HAND,R_BETA_HAND,R_TAU_ALPHA_SHOULDER)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 12:14:47

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
t4 = sin(r_Alpha_Hand);
t5 = sin(r_Beta_Hand);
t6 = dr_Beta_Hand.^2;
t7 = dr_Alpha_Hand.^2;
t8 = length_Hand.^2;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t13 = m_Hand.*t8;
t14 = (g.*length_Hand.*m_Hand.*t2)./2.0;
t15 = t9.*t13.*3.0;
t16 = t10.*t11.*t13.*3.0;
t17 = t11.*t12.*t13.*3.0;
t18 = (t2.*t4.*t7.*t13)./4.0;
t20 = (t2.*t4.*t6.*t10.*t13)./4.0;
t22 = (t2.*t4.*t6.*t12.*t13)./4.0;
t19 = -t18;
t21 = t10.*t18;
t23 = t12.*t18;
t24 = t13+t15+t16+t17;
t25 = 1.0./t24;
A11 = t8.*t11.*t12.*t25.*-1.2e+1;
if nargout > 1
    t30 = r_Tau_Alpha_Shoulder+t14+t19+t20+t21+t22+t23;
    t26 = t2.*t3.*t4.*t8.*t25.*1.2e+1;
    t27 = t2.*t4.*t5.*t8.*t25.*1.2e+1;
    t29 = t3.*t5.*t8.*t11.*t25.*1.2e+1;
    A12 = t29;
end
if nargout > 2
    t28 = -t27;
    A13 = t28;
end
if nargout > 3
    A14 = -ddr_Beta_Hand.*length_Hand.*t2.*t3+length_Hand.*t2.*t5.*t6+length_Hand.*t2.*t5.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t3.*t4.*2.0-length_Hand.*t4.*t5.*t25.*t30.*1.2e+1;
end
if nargout > 4
    A21 = t29;
end
if nargout > 5
    A22 = t8.*t10.*t11.*t25.*-1.2e+1;
end
if nargout > 6
    A23 = t26;
end
if nargout > 7
    A24 = -ddr_Beta_Hand.*length_Hand.*t2.*t5-length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t25.*t30.*1.2e+1;
end
if nargout > 8
    A31 = t28;
end
if nargout > 9
    A32 = t26;
end
if nargout > 10
    A33 = t8.*t9.*t25.*-1.2e+1;
end
if nargout > 11
    A34 = -length_Hand.*t4.*t7-length_Hand.*t2.*t25.*t30.*1.2e+1;
end
