function ddr_Arm_Bottom = find_Ddr_Arm_Bottom(dr_Beta_Hand,dr_Alpha_Hand,g,length_Hand,m_Hand,r_Alpha_Hand,r_Beta_Hand,r_F_X,r_F_Y,r_F_Z,r_Tau_Alpha_Shoulder)
%FIND_DDR_ARM_BOTTOM
%    DDR_ARM_BOTTOM = FIND_DDR_ARM_BOTTOM(DR_BETA_HAND,DR_ALPHA_HAND,G,LENGTH_HAND,M_HAND,R_ALPHA_HAND,R_BETA_HAND,R_F_X,R_F_Y,R_F_Z,R_TAU_ALPHA_SHOULDER)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Jun-2021 23:36:54

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
t4 = sin(r_Alpha_Hand);
t5 = sin(r_Beta_Hand);
t6 = dr_Beta_Hand.^2;
t7 = dr_Alpha_Hand.^2;
t8 = length_Hand.^2;
t13 = 1.0./length_Hand;
t14 = 1.0./m_Hand;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t15 = length_Hand.*r_F_Z.*t2;
t16 = m_Hand.*t8;
t17 = length_Hand.*r_F_X.*t4.*t5;
t18 = length_Hand.*r_F_X.*t2.*t3;
t19 = length_Hand.*r_F_Y.*t2.*t5;
t20 = length_Hand.*r_F_Y.*t3.*t4;
t21 = (g.*length_Hand.*m_Hand.*t2)./2.0;
t22 = -t20;
t23 = t9.*t10.*3.0;
t24 = t9.*t16.*3.0;
t25 = t9.*t12.*3.0;
t26 = t10.*t11.*t16.*3.0;
t27 = t11.*t12.*t16.*3.0;
t28 = (t2.*t4.*t7.*t16)./4.0;
t30 = (dr_Beta_Hand.*dr_Alpha_Hand.*t2.*t4.*t10.*t16)./2.0;
t31 = (dr_Beta_Hand.*dr_Alpha_Hand.*t2.*t4.*t12.*t16)./2.0;
t32 = (t2.*t4.*t6.*t10.*t16)./4.0;
t34 = (t2.*t4.*t6.*t12.*t16)./4.0;
t29 = -t28;
t33 = t10.*t28;
t35 = t12.*t28;
t36 = t23+t25+1.0;
t38 = t16+t24+t26+t27;
t40 = t18+t19+t30+t31;
t37 = 1.0./t36;
t39 = 1.0./t38;
t41 = r_Tau_Alpha_Shoulder+t15+t17+t21+t22+t29+t32+t33+t34+t35;
ddr_Arm_Bottom = [length_Hand.*t2.*t5.*t6+length_Hand.*t2.*t5.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t3.*t4.*2.0-length_Hand.*t4.*t5.*t39.*t41.*1.2e+1-t2.*t3.*t13.*t14.*t37.*t40.*1.2e+1,-length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dr_Beta_Hand.*dr_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t39.*t41.*1.2e+1-t2.*t5.*t13.*t14.*t37.*t40.*1.2e+1,-length_Hand.*t4.*t7-length_Hand.*t2.*t39.*t41.*1.2e+1];
