function [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = find_Coeffs_Ddl_Arm_Bottom_FFD(dl_Beta_Hand,dl_Alpha_Hand,g,l_Alpha_Hand,l_Beta_Hand,l_Tau_Beta_Shoulder,l_Tau_Alpha_Shoulder,length_Hand,m_Hand)
%FIND_COEFFS_DDL_ARM_BOTTOM_FFD
%    [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = FIND_COEFFS_DDL_ARM_BOTTOM_FFD(DL_BETA_HAND,DL_ALPHA_HAND,G,L_ALPHA_HAND,L_BETA_HAND,L_TAU_BETA_SHOULDER,L_TAU_ALPHA_SHOULDER,LENGTH_HAND,M_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 15:28:07

t2 = cos(l_Alpha_Hand);
t3 = cos(l_Beta_Hand);
t4 = sin(l_Alpha_Hand);
t5 = sin(l_Beta_Hand);
t6 = dl_Beta_Hand.^2;
t7 = dl_Alpha_Hand.^2;
t8 = length_Hand.^2;
t13 = -l_Tau_Beta_Shoulder;
t14 = 1.0./length_Hand;
t15 = 1.0./m_Hand;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t16 = m_Hand.*t8;
t19 = (g.*length_Hand.*m_Hand.*t2)./2.0;
t17 = l_Tau_Alpha_Shoulder.*t12;
t18 = l_Tau_Alpha_Shoulder.*t10;
t20 = t9.*t10.*3.0;
t21 = t9.*t16.*3.0;
t22 = t9.*t12.*3.0;
t23 = t10.*t11.*t16.*3.0;
t24 = t11.*t12.*t16.*3.0;
t25 = (t2.*t4.*t7.*t16)./4.0;
t27 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t10.*t16)./2.0;
t28 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t12.*t16)./2.0;
t29 = (t2.*t4.*t6.*t10.*t16)./4.0;
t31 = (t2.*t4.*t6.*t12.*t16)./4.0;
t26 = -t25;
t30 = t10.*t25;
t32 = t12.*t25;
t33 = t20+t22+1.0;
t36 = t13+t27+t28;
t37 = t16+t21+t23+t24;
t34 = 1.0./t33;
t38 = 1.0./t37;
A11 = t9.*t10.*t15.*t34.*-1.2e+1-t8.*t11.*t12.*t38.*1.2e+1;
if nargout > 1
    t44 = t17+t18+t19+t26+t29+t30+t31+t32;
    t35 = t3.*t5.*t9.*t15.*t34.*1.2e+1;
    t39 = t2.*t3.*t4.*t8.*t38.*1.2e+1;
    t40 = t2.*t4.*t5.*t8.*t38.*1.2e+1;
    t41 = t3.*t5.*t8.*t11.*t38.*1.2e+1;
    t42 = -t41;
    t43 = t35+t42;
    A12 = t43;
end
if nargout > 2
    A13 = t40;
end
if nargout > 3
    A14 = -length_Hand.*t2.*t5.*t6-length_Hand.*t2.*t5.*t7-dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t3.*t4.*2.0+length_Hand.*t4.*t5.*t38.*t44.*1.2e+1+t2.*t3.*t14.*t15.*t34.*t36.*1.2e+1;
end
if nargout > 4
    A21 = t43;
end
if nargout > 5
    A22 = t8.*t10.*t11.*t38.*-1.2e+1-t9.*t12.*t15.*t34.*1.2e+1;
end
if nargout > 6
    A23 = t39;
end
if nargout > 7
    A24 = -length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t38.*t44.*1.2e+1-t2.*t5.*t14.*t15.*t34.*t36.*1.2e+1;
end
if nargout > 8
    A31 = t40;
end
if nargout > 9
    A32 = t39;
end
if nargout > 10
    A33 = t8.*t9.*t38.*-1.2e+1;
end
if nargout > 11
    A34 = -length_Hand.*t4.*t7-length_Hand.*t2.*t38.*t44.*1.2e+1;
end
