function [A11,A12,A21,A22,A31,A32] = find_Coeffs_Ddl_Shoulder_Tau_Beta_HFD(alpha_Body,beta_Body,depth_Body,gamma_Body,height_Body,m_Body,width_Body)
%FIND_COEFFS_DDL_SHOULDER_TAU_BETA_HFD
%    [A11,A12,A21,A22,A31,A32] = FIND_COEFFS_DDL_SHOULDER_TAU_BETA_HFD(ALPHA_BODY,BETA_BODY,DEPTH_BODY,GAMMA_BODY,HEIGHT_BODY,M_BODY,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 16:39:36

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = sin(beta_Body);
t7 = sin(gamma_Body);
t8 = depth_Body.^2;
t9 = height_Body.^2;
t10 = width_Body.^2;
t14 = 1.0./m_Body;
t11 = t2.^2;
t12 = t4.^2;
t13 = t5.^2;
t15 = m_Body.*t8;
t16 = m_Body.*t10;
t17 = t9+t10;
t18 = 1.0./t17;
t19 = t15+t16;
t20 = 1.0./t19;
t21 = height_Body.*t2.*t4.*t14.*t18.*6.0;
t22 = height_Body.*t2.*t5.*t7.*t14.*t18.*6.0;
t23 = t2.*t3.*t7.*t14.*t18.*width_Body.*6.0;
t24 = height_Body.*t7.*t11.*t14.*t18.*6.0;
t26 = t2.*t3.*t4.*t5.*t14.*t18.*width_Body.*6.0;
t29 = t3.*t4.*t11.*t14.*t18.*width_Body.*6.0;
t25 = -t23;
t27 = t3.*t4.*t13.*t20.*width_Body.*6.0;
t28 = t5.*t6.*t12.*t20.*width_Body.*6.0;
t30 = t2.*t3.*t4.*t5.*t20.*width_Body.*6.0;
t33 = t4.*t6.*t7.*t13.*t20.*width_Body.*6.0;
t34 = t2.*t4.*t5.*t6.*t7.*t20.*width_Body.*6.0;
t31 = -t28;
t32 = -t30;
t35 = -t33;
t36 = -t34;
t37 = t21+t25+t31;
A11 = t37;
if nargout > 1
    A12 = t37;
end
if nargout > 2
    t38 = t24+t27+t29+t36;
    A21 = t38;
end
if nargout > 3
    A22 = t38;
end
if nargout > 4
    t39 = t22+t26+t32+t35;
    A31 = t39;
end
if nargout > 5
    A32 = t39;
end
