function l_Shoulder = FRD_L_Shoulder(alpha_Body,beta_Body,gamma_Body,width_Body,x_Head,y_Head,z_Head)
%FRD_L_SHOULDER
%    L_SHOULDER = FRD_L_SHOULDER(ALPHA_BODY,BETA_BODY,GAMMA_BODY,WIDTH_BODY,X_HEAD,Y_HEAD,Z_HEAD)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 17:37:42

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = sin(alpha_Body);
t5 = sin(beta_Body);
t6 = sin(gamma_Body);
l_Shoulder = [x_Head-(t3.*width_Body.*cos(gamma_Body))./2.0,y_Head-(t4.*t5.*width_Body)./2.0-(t2.*t3.*t6.*width_Body)./2.0,z_Head+(t2.*t5.*width_Body)./2.0-(t3.*t4.*t6.*width_Body)./2.0];
