function [A11,A12,A13] = HFD_Coeffs_R_Tau_Beta_Shoulder_Force(ddr_Beta_Hand,dr_Beta_Hand,dr_Alpha_Hand,length_Hand,m_Hand,r_Alpha_Hand,r_Beta_Hand)
%HFD_COEFFS_R_TAU_BETA_SHOULDER_FORCE
%    [A11,A12,A13] = HFD_COEFFS_R_TAU_BETA_SHOULDER_FORCE(DDR_BETA_HAND,DR_BETA_HAND,DR_ALPHA_HAND,LENGTH_HAND,M_HAND,R_ALPHA_HAND,R_BETA_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 16:54:22

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
A11 = length_Hand.*t2.*t3;
if nargout > 1
    t4 = sin(r_Alpha_Hand);
    t5 = sin(r_Beta_Hand);
    A12 = length_Hand.*t2.*t5;
end
if nargout > 2
    t6 = length_Hand.^2;
    t7 = t2.^2;
    t8 = t3.^2;
    t9 = t5.^2;
    A13 = ddr_Beta_Hand.*m_Hand.*t6.*(-1.0./1.2e+1)-(ddr_Beta_Hand.*m_Hand.*t6.*t7.*t8)./4.0-(ddr_Beta_Hand.*m_Hand.*t6.*t7.*t9)./4.0+(dr_Beta_Hand.*dr_Alpha_Hand.*m_Hand.*t2.*t4.*t6.*t8)./2.0+(dr_Beta_Hand.*dr_Alpha_Hand.*m_Hand.*t2.*t4.*t6.*t9)./2.0;
end
