function [A11,A12,A13] = HFD_Coeffs_R_Tau_Beta_Shoulder_Force(length_Hand,r_Alpha_Hand,r_Beta_Hand)
%HFD_COEFFS_R_TAU_BETA_SHOULDER_FORCE
%    [A11,A12,A13] = HFD_COEFFS_R_TAU_BETA_SHOULDER_FORCE(LENGTH_HAND,R_ALPHA_HAND,R_BETA_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:36:46

t2 = cos(r_Alpha_Hand);
t3 = sin(r_Alpha_Hand);
t4 = sin(r_Beta_Hand);
t5 = t2.^2;
t6 = t3.^2;
t7 = t5+t6;
t8 = 1.0./t7;
A11 = length_Hand.*t8.*cos(r_Beta_Hand);
if nargout > 1
    A12 = length_Hand.*t2.*t4.*t8;
end
if nargout > 2
    A13 = length_Hand.*t3.*t4.*t8;
end
