function [A11,A12,A13,A21,A22,A23,A31,A32,A33] = HFD_Coeffs_Ddl_Arm_Bottom_Force(l_Alpha_Hand,l_Beta_Hand,length_Hand,m_Hand)
%HFD_COEFFS_DDL_ARM_BOTTOM_FORCE
%    [A11,A12,A13,A21,A22,A23,A31,A32,A33] = HFD_COEFFS_DDL_ARM_BOTTOM_FORCE(L_ALPHA_HAND,L_BETA_HAND,LENGTH_HAND,M_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:36:57

A11 = 0.0;
if nargout > 1
    A12 = 0.0;
end
if nargout > 2
    A13 = 0.0;
end
if nargout > 3
    A21 = 0.0;
end
if nargout > 4
    t2 = cos(l_Alpha_Hand);
    t3 = cos(l_Beta_Hand);
    t4 = sin(l_Alpha_Hand);
    t5 = length_Hand.^2;
    t6 = t2.^2;
    t7 = t3.^2;
    t8 = t4.^2;
    t9 = m_Hand.*t5;
    t10 = t7.*t8.*t9.*3.0;
    t11 = t6.*t7.*t9.*3.0;
    t12 = t9+t10+t11;
    t13 = 1.0./t12;
    A22 = t5.*t7.*t8.*t13.*-1.2e+1;
end
if nargout > 5
    t14 = t2.*t4.*t5.*t7.*t13.*1.2e+1;
    A23 = t14;
end
if nargout > 6
    A31 = 0.0;
end
if nargout > 7
    A32 = t14;
end
if nargout > 8
    A33 = t5.*t6.*t7.*t13.*-1.2e+1;
end
