function [A11,A12,A13,A21,A22,A23,A31,A32,A33] = HFD_Coeffs_Ddr_Arm_Bottom_Force(length_Hand,m_Hand,r_Alpha_Hand,r_Beta_Hand)
%HFD_COEFFS_DDR_ARM_BOTTOM_FORCE
%    [A11,A12,A13,A21,A22,A23,A31,A32,A33] = HFD_COEFFS_DDR_ARM_BOTTOM_FORCE(LENGTH_HAND,M_HAND,R_ALPHA_HAND,R_BETA_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 16:54:22

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
t4 = sin(r_Alpha_Hand);
t5 = sin(r_Beta_Hand);
t6 = length_Hand.^2;
t7 = t2.^2;
t8 = t3.^2;
t9 = t4.^2;
t10 = t5.^2;
t11 = m_Hand.*t6;
t12 = t7.*t11.*3.0;
t13 = t8.*t9.*t11.*3.0;
t14 = t9.*t10.*t11.*3.0;
t15 = t11+t12+t13+t14;
t16 = 1.0./t15;
A11 = t6.*t9.*t10.*t16.*-1.2e+1;
if nargout > 1
    t17 = t2.*t3.*t4.*t6.*t16.*1.2e+1;
    t18 = t2.*t4.*t5.*t6.*t16.*1.2e+1;
    t20 = t3.*t5.*t6.*t9.*t16.*1.2e+1;
    A12 = t20;
end
if nargout > 2
    t19 = -t18;
    A13 = t19;
end
if nargout > 3
    A21 = t20;
end
if nargout > 4
    A22 = t6.*t8.*t9.*t16.*-1.2e+1;
end
if nargout > 5
    A23 = t17;
end
if nargout > 6
    A31 = t19;
end
if nargout > 7
    A32 = t17;
end
if nargout > 8
    A33 = t6.*t7.*t16.*-1.2e+1;
end
