function [A11,A21,A31] = HFD_Coeffs_Ddl_Shoulder_Constant(alpha_Body,beta_Body,dalpha_Body,dbeta_Body,depth_Body,dgamma_Body,g,gamma_Body,height_Body,l_Tau_Alpha_Shoulder,m_Body,r_Tau_Alpha_Shoulder,width_Body)
%HFD_COEFFS_DDL_SHOULDER_CONSTANT
%    [A11,A21,A31] = HFD_COEFFS_DDL_SHOULDER_CONSTANT(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DBETA_BODY,DEPTH_BODY,DGAMMA_BODY,G,GAMMA_BODY,HEIGHT_BODY,L_TAU_ALPHA_SHOULDER,M_BODY,R_TAU_ALPHA_SHOULDER,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:16:37

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = sin(beta_Body);
t7 = sin(gamma_Body);
t8 = g.*m_Body;
t9 = l_Tau_Alpha_Shoulder+r_Tau_Alpha_Shoulder;
t10 = dalpha_Body.^2;
t11 = dbeta_Body.^2;
t12 = depth_Body.^2;
t13 = dgamma_Body.^2;
t14 = height_Body.^2;
t15 = height_Body.^3;
t17 = width_Body.^2;
t22 = 1.0./m_Body;
t16 = t14.^2;
t18 = t2.^2;
t19 = t4.^2;
t20 = t5.^2;
t21 = t7.^2;
t23 = -t8;
t24 = m_Body.*t12;
t25 = m_Body.*t17;
t26 = t12.*t14;
t27 = t12+t14;
t28 = t12.*t17;
t29 = t14.*t17;
t30 = t14+t17;
t31 = dalpha_Body.*dgamma_Body.*height_Body.*t5.*t7;
t33 = dalpha_Body.*dgamma_Body.*height_Body.*m_Body.*t2.*t7;
t34 = height_Body.*t2.*t4.*t10.*2.0;
t35 = height_Body.*t2.*t4.*t13.*2.0;
t40 = (height_Body.*t2.*t4.*t8)./2.0;
t41 = (height_Body.*t5.*t7.*t8)./2.0;
t43 = (height_Body.*t2.*t4.*t10)./2.0;
t44 = (height_Body.*t2.*t4.*t13)./2.0;
t49 = (height_Body.*m_Body.*t4.*t5.*t10)./2.0;
t50 = (height_Body.*m_Body.*t4.*t5.*t13)./2.0;
t55 = (m_Body.*t4.*t7.*t13.*t14)./4.0;
t32 = t31.*4.0;
t36 = -t31;
t38 = 1.0./t27;
t39 = 1.0./t30;
t42 = t24+t25;
t45 = -t40;
t46 = -t41;
t47 = t2.*t5.*t16.*t19;
t48 = t2.*t5.*t16.*t21;
t53 = t2.*t5.*t21.*t26;
t54 = t2.*t5.*t19.*t29;
t56 = -t55;
t58 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t7.*t14.*t18)./2.0;
t59 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t7.*t14.*t20)./2.0;
t60 = (m_Body.*t4.*t7.*t10.*t14.*t18)./4.0;
t61 = t18.*t55;
t62 = (m_Body.*t4.*t7.*t10.*t14.*t20)./4.0;
t63 = t20.*t55;
t65 = t16+t26+t28+t29;
t69 = t23+t33+t49+t50;
t37 = -t32;
t51 = 1.0./t42;
t52 = -t48;
t57 = -t53;
t64 = t4.*t7.*t13.*t14.*t39.*3.0;
t66 = 1.0./t65;
t68 = t36+t43+t44;
t73 = t9+t45+t58+t59;
t75 = height_Body.*t5.*t7.*t22.*t39.*t69.*6.0;
t76 = height_Body.*t2.*t4.*t22.*t38.*t69.*6.0;
t80 = t46+t56+t60+t61+t62+t63;
t67 = t34+t35+t37;
t74 = t47+t52+t54+t57;
t77 = -t75;
t78 = -t76;
t79 = t22.*t38.*t73.*1.2e+1;
t81 = t22.*t39.*t80.*1.2e+1;
t70 = height_Body.*t4.*t5.*t38.*t67.*(3.0./2.0);
t71 = height_Body.*t2.*t7.*t39.*t67.*(3.0./2.0);
t72 = -t71;
t82 = t70+t78+t79;
t83 = t64+t72+t77+t81;
A11 = (t3.*t4.*t11.*width_Body)./2.0+(t3.*t4.*t13.*width_Body)./2.0-(t3.*t7.*t83.*width_Body)./2.0-(height_Body.*t7.*t13.*t39.*(t30+t14.*t19.*3.0))./2.0-dbeta_Body.*dgamma_Body.*t6.*t7.*width_Body-height_Body.*t4.*t22.*t39.*t80.*6.0+t2.*t4.*t7.*t14.*t39.*t67.*(3.0./4.0)-t4.*t6.*t7.*t9.*t51.*width_Body.*6.0+t4.*t5.*t7.*t14.*t22.*t39.*t69.*3.0;
if nargout > 1
    A21 = t66.*t68.*(t65+t16.*t18.*t21.*3.0+t16.*t19.*t20.*3.0+t18.*t21.*t26.*3.0+t19.*t20.*t29.*3.0)-t22.*t66.*t69.*t74.*3.0+(t5.*t6.*t10.*width_Body)./2.0+(t5.*t6.*t11.*width_Body)./2.0-(t2.*t6.*t82.*width_Body)./2.0-dalpha_Body.*dbeta_Body.*t2.*t3.*width_Body+(t2.*t3.*t7.*t10.*width_Body)./2.0+(t2.*t3.*t7.*t11.*width_Body)./2.0+(t2.*t3.*t7.*t13.*width_Body)./2.0+(t2.*t3.*t4.*t83.*width_Body)./2.0+(t3.*t5.*t7.*t82.*width_Body)./2.0+height_Body.*t4.*t5.*t22.*t38.*t73.*6.0-height_Body.*t2.*t7.*t22.*t39.*t80.*6.0-t2.*t4.*t13.*t15.*t21.*t39.*(3.0./2.0)+t3.*t5.*t7.*t9.*t51.*width_Body.*6.0-t2.*t6.*t9.*t21.*t51.*width_Body.*6.0-dalpha_Body.*dbeta_Body.*t5.*t6.*t7.*width_Body+dalpha_Body.*dgamma_Body.*t3.*t4.*t5.*width_Body+dbeta_Body.*dgamma_Body.*t2.*t4.*t6.*width_Body;
end
if nargout > 2
    A31 = t66.*t68.*t74.*-3.0-(t2.*t6.*t10.*width_Body)./2.0-(t2.*t6.*t11.*width_Body)./2.0-(t5.*t6.*t82.*width_Body)./2.0+t22.*t66.*t69.*(t65+t16.*t18.*t19.*3.0+t16.*t20.*t21.*3.0+t18.*t19.*t29.*3.0+t20.*t21.*t26.*3.0)-dalpha_Body.*dbeta_Body.*t3.*t5.*width_Body+(t3.*t5.*t7.*t10.*width_Body)./2.0+(t3.*t5.*t7.*t11.*width_Body)./2.0+(t3.*t5.*t7.*t13.*width_Body)./2.0-(t2.*t3.*t7.*t82.*width_Body)./2.0+(t3.*t4.*t5.*t83.*width_Body)./2.0-height_Body.*t2.*t4.*t22.*t38.*t73.*6.0-height_Body.*t5.*t7.*t22.*t39.*t80.*6.0-t4.*t5.*t13.*t15.*t21.*t39.*(3.0./2.0)-t2.*t3.*t7.*t9.*t51.*width_Body.*6.0-t5.*t6.*t9.*t21.*t51.*width_Body.*6.0+dalpha_Body.*dbeta_Body.*t2.*t6.*t7.*width_Body-dalpha_Body.*dgamma_Body.*t2.*t3.*t4.*width_Body+dbeta_Body.*dgamma_Body.*t4.*t5.*t6.*width_Body;
end
