function [A11,A12,A13] = HFD_Coeffs_L_Tau_Beta_Shoulder_Force(ddl_Beta_Hand,dl_Beta_Hand,dl_Alpha_Hand,l_Alpha_Hand,l_Beta_Hand,length_Hand,m_Hand)
%HFD_COEFFS_L_TAU_BETA_SHOULDER_FORCE
%    [A11,A12,A13] = HFD_COEFFS_L_TAU_BETA_SHOULDER_FORCE(DDL_BETA_HAND,DL_BETA_HAND,DL_ALPHA_HAND,L_ALPHA_HAND,L_BETA_HAND,LENGTH_HAND,M_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 17:21:59

t2 = cos(l_Alpha_Hand);
t3 = cos(l_Beta_Hand);
A11 = -length_Hand.*t2.*t3;
if nargout > 1
    t4 = sin(l_Alpha_Hand);
    t5 = sin(l_Beta_Hand);
    A12 = length_Hand.*t2.*t5;
end
if nargout > 2
    t6 = length_Hand.^2;
    t7 = t2.^2;
    t8 = t3.^2;
    t9 = t5.^2;
    A13 = ddl_Beta_Hand.*m_Hand.*t6.*(-1.0./1.2e+1)-(ddl_Beta_Hand.*m_Hand.*t6.*t7.*t8)./4.0-(ddl_Beta_Hand.*m_Hand.*t6.*t7.*t9)./4.0+(dl_Beta_Hand.*dl_Alpha_Hand.*m_Hand.*t2.*t4.*t6.*t8)./2.0+(dl_Beta_Hand.*dl_Alpha_Hand.*m_Hand.*t2.*t4.*t6.*t9)./2.0;
end
