function coeffs_Ddl_Arm_Bottom = find_Coeffs_Ddl_Arm_Bottom(dl_Beta_Hand,dl_Alpha_Hand,g,l_Alpha_Hand,l_Beta_Hand,length_Hand,m_Hand)
%FIND_COEFFS_DDL_ARM_BOTTOM
%    COEFFS_DDL_ARM_BOTTOM = FIND_COEFFS_DDL_ARM_BOTTOM(DL_BETA_HAND,DL_ALPHA_HAND,G,L_ALPHA_HAND,L_BETA_HAND,LENGTH_HAND,M_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Jun-2021 11:50:37

t2 = cos(l_Alpha_Hand);
t3 = cos(l_Beta_Hand);
t4 = sin(l_Alpha_Hand);
t5 = sin(l_Beta_Hand);
t6 = dl_Beta_Hand.^2;
t7 = dl_Alpha_Hand.^2;
t8 = length_Hand.^2;
t13 = 1.0./length_Hand;
t14 = 1.0./m_Hand;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t15 = m_Hand.*t8;
t16 = (g.*length_Hand.*m_Hand.*t2)./2.0;
t17 = t9.*t10.*3.0;
t18 = t9.*t15.*3.0;
t19 = t9.*t12.*3.0;
t20 = t10.*t11.*t15.*3.0;
t21 = t11.*t12.*t15.*3.0;
t22 = (t2.*t4.*t7.*t15)./4.0;
t24 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t10.*t15)./2.0;
t25 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t12.*t15)./2.0;
t26 = (t2.*t4.*t6.*t10.*t15)./4.0;
t28 = (t2.*t4.*t6.*t12.*t15)./4.0;
t23 = -t22;
t27 = t10.*t22;
t29 = t12.*t22;
t30 = t17+t19+1.0;
t32 = t24+t25;
t34 = t15+t18+t20+t21;
t31 = 1.0./t30;
t35 = 1.0./t34;
t40 = t16+t23+t26+t27+t28+t29;
t33 = t3.*t5.*t9.*t14.*t31.*1.2e+1;
t36 = t2.*t3.*t4.*t8.*t35.*1.2e+1;
t37 = t2.*t4.*t5.*t8.*t35.*1.2e+1;
t38 = t3.*t5.*t8.*t11.*t35.*1.2e+1;
t39 = -t38;
t41 = t33+t39;
coeffs_Ddl_Arm_Bottom = reshape([t9.*t10.*t14.*t31.*-1.2e+1-t8.*t11.*t12.*t35.*1.2e+1,t41,t37,t41,t8.*t10.*t11.*t35.*-1.2e+1-t9.*t12.*t14.*t31.*1.2e+1,t36,t37,t36,t8.*t9.*t35.*-1.2e+1,-length_Hand.*t2.*t5.*t6-length_Hand.*t2.*t5.*t7-dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t3.*t4.*2.0+length_Hand.*t4.*t5.*t35.*t40.*1.2e+1+t2.*t3.*t13.*t14.*t31.*t32.*1.2e+1,-length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t35.*t40.*1.2e+1-t2.*t5.*t13.*t14.*t31.*t32.*1.2e+1,-length_Hand.*t4.*t7-length_Hand.*t2.*t35.*t40.*1.2e+1],[3,4]);
