function [dbeta_Body,dx_Head,dy_Head,dz_Head] = find_Restrained_Velocity(alpha_Body,beta_Body,dalpha_Body,dgamma_Body,dl_Beta_Hand,dl_Alpha_Hand,dr_Beta_Hand,dr_Alpha_Hand,gamma_Body,l_Alpha_Hand,l_Beta_Hand,length_Hand,r_Alpha_Hand,r_Beta_Hand,width_Body)
%FIND_RESTRAINED_VELOCITY
%    [DBETA_BODY,DX_HEAD,DY_HEAD,DZ_HEAD] = FIND_RESTRAINED_VELOCITY(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DGAMMA_BODY,DL_BETA_HAND,DL_ALPHA_HAND,DR_BETA_HAND,DR_ALPHA_HAND,GAMMA_BODY,L_ALPHA_HAND,L_BETA_HAND,LENGTH_HAND,R_ALPHA_HAND,R_BETA_HAND,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Jun-2021 11:16:09

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = cos(l_Alpha_Hand);
t6 = cos(l_Beta_Hand);
t7 = sin(alpha_Body);
t8 = cos(r_Alpha_Hand);
t9 = cos(r_Beta_Hand);
t10 = sin(beta_Body);
t11 = sin(gamma_Body);
t12 = sin(l_Alpha_Hand);
t13 = sin(l_Beta_Hand);
t14 = sin(r_Alpha_Hand);
t15 = sin(r_Beta_Hand);
t16 = 1.0./width_Body;
t17 = t2.*t3;
t18 = t3.*t7;
t19 = dalpha_Body.*t2.*t10;
t20 = t2.*t10.*t11;
t21 = dl_Beta_Hand.*length_Hand.*t5.*t13;
t22 = dl_Alpha_Hand.*length_Hand.*t6.*t12;
t23 = t7.*t10.*t11;
t24 = dr_Beta_Hand.*length_Hand.*t8.*t15;
t25 = dr_Alpha_Hand.*length_Hand.*t9.*t14;
t26 = dgamma_Body.*t4.*t17;
t27 = dalpha_Body.*t11.*t18;
t28 = -t20;
t30 = t17+t23;
t29 = -t27;
t31 = t18+t28;
t32 = 1.0./t31;
t33 = t19+t26+t29;
t34 = (t33.*width_Body)./2.0;
t35 = -t34;
t36 = t24+t25+t34;
t37 = t21+t22+t35;
dbeta_Body = -t16.*t32.*t36+t16.*t32.*t37;
if nargout > 1
    dx_Head = dl_Beta_Hand.*length_Hand.*t5.*t6-dl_Alpha_Hand.*length_Hand.*t12.*t13-(dgamma_Body.*t3.*t11.*width_Body)./2.0+(t4.*t10.*t32.*t36)./2.0-(t4.*t10.*t32.*t37)./2.0;
end
if nargout > 2
    dy_Head = t21.*(-1.0./2.0)-t22./2.0-t24./2.0-t25./2.0;
end
if nargout > 3
    dz_Head = width_Body.*(dalpha_Body.*t7.*t10+dalpha_Body.*t11.*t17+dgamma_Body.*t4.*t18).*(-1.0./2.0)+dr_Alpha_Hand.*length_Hand.*t8-(t30.*t32.*t36)./2.0+(t30.*t32.*t37)./2.0;
end
