function l_Shoulder = find_L_Shoulder(alpha_Body,beta_Body,gamma_Body,offset_Body,width_Body)
%FIND_L_SHOULDER
%    L_SHOULDER = FIND_L_SHOULDER(ALPHA_BODY,BETA_BODY,GAMMA_BODY,OFFSET_BODY,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Jun-2021 19:45:20

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = sin(alpha_Body);
t5 = sin(beta_Body);
t6 = sin(gamma_Body);
l_Shoulder = [t3.*width_Body.*cos(gamma_Body).*(-1.0./2.0),width_Body.*(t4.*t5+t2.*t3.*t6).*(-1.0./2.0)+offset_Body.*t2,(width_Body.*(t2.*t5-t3.*t4.*t6))./2.0+offset_Body.*t4];
