function ddl_Arm_Bottom = find_Ddl_Arm_Bottom(dl_Beta_Hand,dl_Alpha_Hand,g,l_Alpha_Hand,l_Beta_Hand,l_F_X,l_F_Y,l_F_Z,length_Hand,m_Hand)
%FIND_DDL_ARM_BOTTOM
%    DDL_ARM_BOTTOM = FIND_DDL_ARM_BOTTOM(DL_BETA_HAND,DL_ALPHA_HAND,G,L_ALPHA_HAND,L_BETA_HAND,L_F_X,L_F_Y,L_F_Z,LENGTH_HAND,M_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Jun-2021 20:12:01

t2 = cos(l_Alpha_Hand);
t3 = cos(l_Beta_Hand);
t4 = sin(l_Alpha_Hand);
t5 = sin(l_Beta_Hand);
t6 = dl_Beta_Hand.^2;
t7 = dl_Alpha_Hand.^2;
t8 = length_Hand.^2;
t13 = 1.0./length_Hand;
t14 = 1.0./m_Hand;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t15 = l_F_Z.*length_Hand.*t2;
t16 = m_Hand.*t8;
t18 = l_F_X.*length_Hand.*t2.*t3;
t19 = l_F_Y.*length_Hand.*t2.*t5;
t20 = l_F_Y.*length_Hand.*t3.*t4;
t21 = l_F_X.*length_Hand.*t4.*t5;
t22 = (g.*length_Hand.*m_Hand.*t2)./2.0;
t17 = -t15;
t23 = -t19;
t24 = t9.*t10.*3.0;
t25 = t9.*t16.*3.0;
t26 = t9.*t12.*3.0;
t27 = t10.*t11.*t16.*3.0;
t28 = t11.*t12.*t16.*3.0;
t29 = (t2.*t4.*t7.*t16)./4.0;
t31 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t10.*t16)./2.0;
t32 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t12.*t16)./2.0;
t33 = (t2.*t4.*t6.*t10.*t16)./4.0;
t35 = (t2.*t4.*t6.*t12.*t16)./4.0;
t30 = -t29;
t34 = t10.*t29;
t36 = t12.*t29;
t37 = t24+t26+1.0;
t39 = t16+t25+t27+t28;
t41 = t18+t23+t31+t32;
t38 = 1.0./t37;
t40 = 1.0./t39;
t42 = t17+t20+t21+t22+t30+t33+t34+t35+t36;
ddl_Arm_Bottom = [-length_Hand.*t2.*t5.*t6-length_Hand.*t2.*t5.*t7-dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t3.*t4.*2.0+length_Hand.*t4.*t5.*t40.*t42.*1.2e+1+t2.*t3.*t13.*t14.*t38.*t41.*1.2e+1,-length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t40.*t42.*1.2e+1-t2.*t5.*t13.*t14.*t38.*t41.*1.2e+1,-length_Hand.*t4.*t7-length_Hand.*t2.*t40.*t42.*1.2e+1];
