function l_Hip = find_L_Hip(alpha_Body,beta_Body,gamma_Body,height_Body,offset_Body,width_Body)
%FIND_L_HIP
%    L_HIP = FIND_L_HIP(ALPHA_BODY,BETA_BODY,GAMMA_BODY,HEIGHT_BODY,OFFSET_BODY,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Jun-2021 19:45:21

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = sin(beta_Body);
t7 = sin(gamma_Body);
l_Hip = [-height_Body.*t7-(t3.*t4.*width_Body)./2.0,width_Body.*(t5.*t6+t2.*t3.*t7).*(-1.0./2.0)+offset_Body.*t2+height_Body.*t2.*t4,(width_Body.*(t2.*t6-t3.*t5.*t7))./2.0+offset_Body.*t5+height_Body.*t4.*t5];
