function [A11,A12,A13,A14,A15,A16,A17,A21,A22,A23,A24,A25,A26,A27,A31,A32,A33,A34,A35,A36,A37] = FFD_Coeffs_Ddl_Shoulder(alpha_Body,beta_Body,dalpha_Body,dbeta_Body,depth_Body,dgamma_Body,g,gamma_Body,height_Body,l_Alpha_Hand,l_Tau_Beta_Shoulder,l_Tau_Alpha_Shoulder,m_Body,r_Beta_Hand,r_Tau_Beta_Shoulder,r_Tau_Alpha_Shoulder,width_Body)
%FFD_COEFFS_DDL_SHOULDER
%    [A11,A12,A13,A14,A15,A16,A17,A21,A22,A23,A24,A25,A26,A27,A31,A32,A33,A34,A35,A36,A37] = FFD_COEFFS_DDL_SHOULDER(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DBETA_BODY,DEPTH_BODY,DGAMMA_BODY,G,GAMMA_BODY,HEIGHT_BODY,L_ALPHA_HAND,L_TAU_BETA_SHOULDER,L_TAU_ALPHA_SHOULDER,M_BODY,R_BETA_HAND,R_TAU_BETA_SHOULDER,R_TAU_ALPHA_SHOULDER,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Jun-2021 09:07:48

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = cos(l_Alpha_Hand);
t6 = sin(alpha_Body);
t7 = cos(r_Beta_Hand);
t8 = sin(beta_Body);
t9 = sin(gamma_Body);
t10 = sin(l_Alpha_Hand);
t11 = sin(r_Beta_Hand);
t12 = g.*m_Body;
t13 = dalpha_Body.^2;
t14 = dbeta_Body.^2;
t15 = depth_Body.^2;
t16 = dgamma_Body.^2;
t17 = height_Body.^2;
t18 = height_Body.^3;
t20 = width_Body.^2;
t30 = 1.0./m_Body;
t19 = t17.^2;
t21 = t2.^2;
t22 = t4.^2;
t23 = t6.^2;
t24 = t8.^2;
t25 = t9.^2;
t26 = l_Tau_Beta_Shoulder.*t5;
t27 = r_Tau_Alpha_Shoulder.*t7;
t28 = l_Tau_Beta_Shoulder.*t10;
t29 = r_Tau_Alpha_Shoulder.*t11;
t31 = -t12;
t32 = m_Body.*t15;
t33 = m_Body.*t20;
t37 = t15.*t17;
t38 = t15+t17;
t39 = t15.*t20;
t40 = t17.*t20;
t41 = t17+t20;
t42 = dalpha_Body.*dgamma_Body.*height_Body.*t6.*t9;
t45 = (t2.*t3.*width_Body)./2.0;
t46 = (t2.*t8.*width_Body)./2.0;
t47 = (t3.*t6.*width_Body)./2.0;
t48 = (t6.*t8.*width_Body)./2.0;
t50 = dalpha_Body.*dgamma_Body.*height_Body.*m_Body.*t2.*t9;
t52 = height_Body.*t2.*t4.*t13.*2.0;
t53 = height_Body.*t2.*t4.*t16.*2.0;
t58 = (height_Body.*t2.*t4.*t12)./2.0;
t60 = (height_Body.*t6.*t9.*t12)./2.0;
t67 = (height_Body.*t2.*t4.*t13)./2.0;
t68 = (height_Body.*t2.*t4.*t16)./2.0;
t70 = t2.*t8.*t9.*width_Body.*(-1.0./2.0);
t71 = t3.*t6.*t9.*width_Body.*(-1.0./2.0);
t79 = (height_Body.*m_Body.*t4.*t6.*t13)./2.0;
t80 = (height_Body.*m_Body.*t4.*t6.*t16)./2.0;
t86 = (m_Body.*t4.*t9.*t16.*t17)./4.0;
t34 = r_Tau_Beta_Shoulder+t26;
t35 = l_Tau_Alpha_Shoulder+t27;
t36 = -t29;
t43 = t42.*4.0;
t44 = t17.*t22.*3.0;
t54 = -t42;
t56 = 1.0./t38;
t57 = 1.0./t41;
t59 = t9.*t45;
t61 = t9.*t46;
t62 = t9.*t47;
t63 = t9.*t48;
t65 = t32+t33;
t69 = -t58;
t72 = t2.*t6.*t19.*t22;
t73 = t2.*t6.*t19.*t25;
t75 = t19.*t21.*t22.*3.0;
t76 = t19.*t21.*t25.*3.0;
t77 = t19.*t22.*t23.*3.0;
t78 = t19.*t23.*t25.*3.0;
t84 = t2.*t6.*t25.*t37;
t85 = t2.*t6.*t22.*t40;
t87 = t21.*t25.*t37.*3.0;
t88 = t21.*t22.*t40.*3.0;
t90 = t23.*t25.*t37.*3.0;
t91 = t22.*t23.*t40.*3.0;
t94 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t9.*t17.*t21)./2.0;
t95 = (dalpha_Body.*dgamma_Body.*m_Body.*t4.*t9.*t17.*t23)./2.0;
t96 = (m_Body.*t4.*t9.*t13.*t17.*t21)./4.0;
t97 = t21.*t86;
t98 = (m_Body.*t4.*t9.*t13.*t17.*t23)./4.0;
t99 = t23.*t86;
t102 = m_Body.*t4.*t9.*t16.*t17.*t21.*(-1.0./4.0);
t104 = m_Body.*t4.*t9.*t16.*t17.*t23.*(-1.0./4.0);
t112 = t46+t71;
t113 = t47+t70;
t124 = t19+t37+t39+t40;
t147 = t31+t50+t79+t80;
t49 = t2.*t34;
t51 = t9.*t35;
t55 = -t43;
t64 = t4.*t6.*t34;
t66 = t28+t36;
t81 = 1.0./t65;
t83 = -t73;
t89 = t41+t44;
t93 = -t84;
t100 = height_Body.*t4.*t30.*t57.*6.0;
t101 = -t96;
t103 = -t98;
t105 = t45+t63;
t106 = t48+t59;
t107 = height_Body.*t2.*t4.*t30.*t56.*6.0;
t108 = height_Body.*t4.*t6.*t30.*t56.*6.0;
t109 = height_Body.*t2.*t9.*t30.*t57.*6.0;
t110 = height_Body.*t6.*t9.*t30.*t57.*6.0;
t111 = t3.*t9.*t30.*t57.*width_Body.*6.0;
t117 = t4.*t9.*t16.*t17.*t57.*3.0;
t118 = t2.*t3.*t4.*t30.*t57.*width_Body.*6.0;
t119 = t3.*t4.*t6.*t30.*t57.*width_Body.*6.0;
t123 = height_Body.*t3.*t4.*t9.*t30.*t57.*width_Body.*3.0;
t125 = t2.*t4.*t9.*t17.*t30.*t57.*3.0;
t126 = t4.*t6.*t9.*t17.*t30.*t57.*3.0;
t127 = height_Body.*t2.*t3.*t22.*t30.*t57.*width_Body.*3.0;
t128 = height_Body.*t2.*t3.*t25.*t30.*t57.*width_Body.*3.0;
t129 = height_Body.*t3.*t6.*t22.*t30.*t57.*width_Body.*3.0;
t130 = height_Body.*t3.*t6.*t25.*t30.*t57.*width_Body.*3.0;
t135 = 1.0./t124;
t138 = height_Body.*t2.*t3.*t4.*t6.*t9.*t30.*t57.*width_Body.*-3.0;
t143 = t54+t67+t68;
t146 = t30.*t56.*t112.*1.2e+1;
t170 = t35+t69+t94+t95;
t178 = height_Body.*t2.*t4.*t30.*t56.*t147.*-6.0;
t180 = t75+t78+t88+t90+t124;
t181 = t76+t77+t87+t91+t124;
t74 = -t64;
t82 = t6.*t66;
t92 = t2.*t4.*t66;
t114 = -t107;
t115 = -t108;
t116 = -t111;
t120 = -t117;
t121 = -t118;
t122 = -t119;
t131 = t2.*t3.*t4.*t8.*t20.*t81.*3.0;
t132 = t3.*t4.*t6.*t8.*t20.*t81.*3.0;
t133 = t20.*t22.*t24.*t81.*3.0;
t134 = t23.*t123;
t136 = t2.*t6.*t123;
t137 = t21.*t123;
t139 = t2.*t4.*t9.*t20.*t24.*t81.*3.0;
t140 = t4.*t6.*t9.*t20.*t24.*t81.*3.0;
t141 = t52+t53+t55;
t142 = t30.*t57.*t89;
t144 = t30.*t56.*t106.*1.2e+1;
t148 = t100+t111;
t149 = t2.*t3.*t81.*t105.*width_Body.*6.0;
t150 = t3.*t6.*t81.*t105.*width_Body.*6.0;
t151 = t4.*t8.*t81.*t105.*width_Body.*6.0;
t152 = t106.*t107;
t153 = t106.*t108;
t155 = t2.*t3.*t81.*t113.*width_Body.*6.0;
t156 = t3.*t6.*t81.*t113.*width_Body.*6.0;
t157 = t4.*t8.*t81.*t113.*width_Body.*6.0;
t158 = t107.*t112;
t159 = t108.*t112;
t160 = t2.*t8.*t9.*t81.*t105.*width_Body.*6.0;
t161 = t6.*t8.*t9.*t81.*t105.*width_Body.*6.0;
t162 = t109+t118;
t163 = t2.*t8.*t9.*t81.*t113.*width_Body.*6.0;
t164 = t110+t119;
t165 = t6.*t8.*t9.*t81.*t113.*width_Body.*6.0;
t171 = t72+t83+t85+t93;
t174 = t108+t146;
t175 = t110.*t147;
t177 = t107.*t147;
t179 = t30.*t56.*t170.*1.2e+1;
t184 = t30.*t135.*t180;
t185 = t30.*t135.*t181;
t145 = t51+t74+t92;
t154 = t100+t116;
A11 = -t123-t133+t142+(t3.*t9.*t154.*width_Body)./2.0;
if nargout > 1
    A12 = t125+t127+t157+(t3.*t9.*t162.*width_Body)./2.0;
end
if nargout > 2
    A13 = t126+t129-t151+(t3.*t9.*t164.*width_Body)./2.0;
end
if nargout > 3
    A14 = t123+t133+t142+(t3.*t9.*t148.*width_Body)./2.0;
end
if nargout > 4
    t166 = t109+t121;
    A15 = t125-t127-t157+(t3.*t9.*t166.*width_Body)./2.0;
end
if nargout > 5
    t167 = t110+t122;
    A16 = t126-t129+t151+(t3.*t9.*t167.*width_Body)./2.0;
end
if nargout > 6
    t168 = height_Body.*t4.*t6.*t56.*t141.*(3.0./2.0);
    t169 = height_Body.*t2.*t9.*t57.*t141.*(3.0./2.0);
    t172 = t107+t144;
    t173 = t114+t144;
    t176 = t115+t146;
    t182 = t30.*t135.*t171.*3.0;
    t186 = t49+t60+t82+t86+t101+t102+t103+t104;
    t183 = -t182;
    t187 = t30.*t57.*t186.*1.2e+1;
    t188 = t168+t178+t179;
    t189 = t120+t169+t175+t187;
    A17 = t126.*t147+t100.*t186+(t3.*t4.*t14.*width_Body)./2.0+(t3.*t4.*t16.*width_Body)./2.0+(t3.*t9.*t189.*width_Body)./2.0-dbeta_Body.*dgamma_Body.*t8.*t9.*width_Body-(height_Body.*t9.*t16.*t57.*t89)./2.0-t4.*t8.*t81.*t145.*width_Body.*6.0+t2.*t4.*t9.*t17.*t57.*t141.*(3.0./4.0);
end
if nargout > 7
    A21 = t125-t128+t132-t139-(t2.*t3.*t4.*t154.*width_Body)./2.0;
end
if nargout > 8
    A22 = t137-t156+t159+t163+t185+t62.*t174-(t2.*t8.*t174.*width_Body)./2.0-(t2.*t3.*t4.*t162.*width_Body)./2.0;
end
if nargout > 9
    A23 = t136+t150+t153-t160+t183-t62.*(t107-t144)+(t2.*t8.*width_Body.*(t107-t144))./2.0-(t2.*t3.*t4.*t164.*width_Body)./2.0;
end
if nargout > 10
    A24 = t125+t128-t132+t139-(t2.*t3.*t4.*t148.*width_Body)./2.0;
end
if nargout > 11
    A25 = t156-t163+t185-t46.*(t108-t146)-t71.*(t108-t146)-(t2.*t3.*t4.*t166.*width_Body)./2.0-height_Body.*t4.*t6.*t30.*t56.*t112.*6.0-height_Body.*t3.*t4.*t9.*t21.*t30.*t57.*width_Body.*3.0;
end
if nargout > 12
    A26 = t138-t150+t160+t183+t46.*t172+t71.*t172-(t2.*t3.*t4.*t167.*width_Body)./2.0-height_Body.*t4.*t6.*t30.*t56.*t106.*6.0;
end
if nargout > 13
    A27 = t13.*t48+t14.*t48+t13.*t59+t14.*t59+t16.*t59+t62.*t188+t108.*t170+t109.*t186+t135.*t143.*t181-t30.*t135.*t147.*t171.*3.0-(t2.*t8.*t188.*width_Body)./2.0-dalpha_Body.*dbeta_Body.*t2.*t3.*width_Body-(t2.*t3.*t4.*t189.*width_Body)./2.0+t3.*t6.*t81.*t145.*width_Body.*6.0-t2.*t4.*t16.*t18.*t25.*t57.*(3.0./2.0)-t2.*t8.*t9.*t81.*t145.*width_Body.*6.0-dalpha_Body.*dbeta_Body.*t6.*t8.*t9.*width_Body+dalpha_Body.*dgamma_Body.*t3.*t4.*t6.*width_Body+dbeta_Body.*dgamma_Body.*t2.*t4.*t8.*width_Body;
end
if nargout > 14
    A31 = t126-t130-t131-t140-(t3.*t4.*t6.*t154.*width_Body)./2.0;
end
if nargout > 15
    A32 = t136+t155+t165+t183-(t6.*t8.*t174.*width_Body)./2.0-(t3.*t4.*t6.*t162.*width_Body)./2.0-(t2.*t3.*t9.*t174.*width_Body)./2.0-height_Body.*t2.*t4.*t30.*t56.*t112.*6.0;
end
if nargout > 16
    A33 = t134-t149-t161+t184+(t6.*t8.*width_Body.*(t107-t144))./2.0-(t3.*t4.*t6.*t164.*width_Body)./2.0+(t2.*t3.*t9.*width_Body.*(t107-t144))./2.0-height_Body.*t2.*t4.*t30.*t56.*t106.*6.0;
end
if nargout > 17
    A34 = t126+t130+t131+t140-(t3.*t4.*t6.*t148.*width_Body)./2.0;
end
if nargout > 18
    A35 = t138-t155+t158-t165+t183-t48.*(t108-t146)-t59.*(t108-t146)-(t3.*t4.*t6.*t166.*width_Body)./2.0;
end
if nargout > 19
    A36 = t149+t152+t161+t184+t48.*t172+t59.*t172-(t3.*t4.*t6.*t167.*width_Body)./2.0-height_Body.*t3.*t4.*t9.*t23.*t30.*t57.*width_Body.*3.0;
end
if nargout > 20
    A37 = t13.*t62+t14.*t62+t16.*t62+t110.*t186+t147.*t184-t135.*t143.*t171.*3.0-(t2.*t8.*t13.*width_Body)./2.0-(t2.*t8.*t14.*width_Body)./2.0-(t6.*t8.*t188.*width_Body)./2.0-dalpha_Body.*dbeta_Body.*t3.*t6.*width_Body-(t2.*t3.*t9.*t188.*width_Body)./2.0-(t3.*t4.*t6.*t189.*width_Body)./2.0-t2.*t3.*t81.*t145.*width_Body.*6.0-height_Body.*t2.*t4.*t30.*t56.*t170.*6.0-t4.*t6.*t16.*t18.*t25.*t57.*(3.0./2.0)-t6.*t8.*t9.*t81.*t145.*width_Body.*6.0+dalpha_Body.*dbeta_Body.*t2.*t8.*t9.*width_Body-dalpha_Body.*dgamma_Body.*t2.*t3.*t4.*width_Body+dbeta_Body.*dgamma_Body.*t4.*t6.*t8.*width_Body;
end
