function [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = FFD_Coeffs_Ddl_Arm_Bottom(dl_Beta_Hand,dl_Alpha_Hand,g,l_Alpha_Hand,l_Beta_Hand,l_Tau_Beta_Shoulder,l_Tau_Alpha_Shoulder,length_Hand,m_Hand)
%FFD_COEFFS_DDL_ARM_BOTTOM
%    [A11,A12,A13,A14,A21,A22,A23,A24,A31,A32,A33,A34] = FFD_COEFFS_DDL_ARM_BOTTOM(DL_BETA_HAND,DL_ALPHA_HAND,G,L_ALPHA_HAND,L_BETA_HAND,L_TAU_BETA_SHOULDER,L_TAU_ALPHA_SHOULDER,LENGTH_HAND,M_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Jun-2021 08:22:52

t2 = cos(l_Alpha_Hand);
t3 = cos(l_Beta_Hand);
t4 = sin(l_Alpha_Hand);
t5 = sin(l_Beta_Hand);
t6 = dl_Beta_Hand.^2;
t7 = dl_Alpha_Hand.^2;
t8 = length_Hand.^2;
t13 = 1.0./length_Hand;
t14 = 1.0./m_Hand;
t9 = t2.^2;
t10 = t3.^2;
t11 = t4.^2;
t12 = t5.^2;
t15 = m_Hand.*t8;
t18 = (g.*length_Hand.*m_Hand.*t2)./2.0;
t16 = l_Tau_Beta_Shoulder.*t11;
t17 = l_Tau_Beta_Shoulder.*t9;
t19 = t9.*t10.*3.0;
t20 = t9.*t15.*3.0;
t21 = t9.*t12.*3.0;
t22 = t10.*t11.*t15.*3.0;
t23 = t11.*t12.*t15.*3.0;
t24 = (t2.*t4.*t7.*t15)./4.0;
t26 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t10.*t15)./2.0;
t27 = (dl_Beta_Hand.*dl_Alpha_Hand.*t2.*t4.*t12.*t15)./2.0;
t28 = (t2.*t4.*t6.*t10.*t15)./4.0;
t31 = (t2.*t4.*t6.*t12.*t15)./4.0;
t25 = -t24;
t29 = t10.*t24;
t30 = -t26;
t32 = t12.*t24;
t33 = -t27;
t34 = t19+t21+1.0;
t37 = t15+t20+t22+t23;
t35 = 1.0./t34;
t38 = 1.0./t37;
A11 = t9.*t10.*t14.*t35.*-1.2e+1-t8.*t11.*t12.*t38.*1.2e+1;
if nargout > 1
    t39 = t16+t17+t30+t33;
    t45 = l_Tau_Alpha_Shoulder+t18+t25+t28+t29+t31+t32;
    t36 = t3.*t5.*t9.*t14.*t35.*1.2e+1;
    t40 = t2.*t3.*t4.*t8.*t38.*1.2e+1;
    t41 = t2.*t4.*t5.*t8.*t38.*1.2e+1;
    t42 = t3.*t5.*t8.*t11.*t38.*1.2e+1;
    t43 = -t42;
    t44 = t36+t43;
    A12 = t44;
end
if nargout > 2
    A13 = t41;
end
if nargout > 3
    A14 = -length_Hand.*t2.*t5.*t6-length_Hand.*t2.*t5.*t7-dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t3.*t4.*2.0+length_Hand.*t4.*t5.*t38.*t45.*1.2e+1-t2.*t3.*t13.*t14.*t35.*t39.*1.2e+1;
end
if nargout > 4
    A21 = t44;
end
if nargout > 5
    A22 = t8.*t10.*t11.*t38.*-1.2e+1-t9.*t12.*t14.*t35.*1.2e+1;
end
if nargout > 6
    A23 = t40;
end
if nargout > 7
    A24 = -length_Hand.*t2.*t3.*t6-length_Hand.*t2.*t3.*t7+dl_Beta_Hand.*dl_Alpha_Hand.*length_Hand.*t4.*t5.*2.0+length_Hand.*t3.*t4.*t38.*t45.*1.2e+1+t2.*t5.*t13.*t14.*t35.*t39.*1.2e+1;
end
if nargout > 8
    A31 = t41;
end
if nargout > 9
    A32 = t40;
end
if nargout > 10
    A33 = t8.*t9.*t38.*-1.2e+1;
end
if nargout > 11
    A34 = -length_Hand.*t4.*t7-length_Hand.*t2.*t38.*t45.*1.2e+1;
end
